
= Current events: 2021-12-09
:toc:
:imagesdir: ../media

== 2021-12-09

Unfortunately, the intended tutorial won't be done due to the illness of the lecturer, Martin Jirkal. I will try to show you the basics, but as it is not really my specialty, it will be very limited and probably not too good. Sorry about that. I will of course be ready for your questions, both live in the lab and online.

== 2021-12-06

Unfortunately, Martin Jirkal, who should have demonstrated the analysis of high level languages this week, contracted Covid and as a result certainly can't give his presentation live. If he can give it at all, it will be online. I will have a more definite information Wednesday evening or Thursday morning.

If the tutorial couldn't be done, please consider it cancelled. You can find the recording of the presentation link:https://kib-files.fit.cvut.cz/mi-rev/recordings/2020/en/tutorial_12.mp4[here]. I will, of course, be available for you at the scheduled time both online and live in the lab, but there's no planned content -- the tutorial will be questions-and-answers only.

== 2021-11-25

In link:https://kos.cvut.cz[KOS], I put up the dates for the early exam. The exam is intended to be live and in order to sign up, you must have the assessment.

== 2021-11-21

Please allow me to bring to your attention (and to mine as well) that the next lecture (December 2nd) won't be on debugging and antidebugging. Instead a guest speaker Jan Rubín from Avast will talk about malware analysis, including a live example. The debugging lecture is postponed until the last week of the semester on December 16th. As a result it makes sense two switch the 11th and 13th tutorial so that you are not forced to solve an antidebugging task before learning about antidebugging. In other words the program for the next weeks is:

* December 2nd:
** Lecture: **Malware analysis** (Jan Rubín, Avast). Note that the lecture **will not** be recorded or streamed, it is intended for live presentation only. Please make sure to attend the lecture if at all possible, it is worth it.
** Tutorial: xref:{imagesdir}/../en/labs/lab13.adoc[Code injection]
* December 9th:
** Tutorial: xref:{imagesdir}/../en/labs/lab12.adoc[.NET analysis] (Martin Jirkal, ESET)
* December 16th:
** Lecture: xref:{imagesdir}/lectures/rev06en.pdf[Debugging and anti-debugging]
** Tutorial: xref:{imagesdir}/../en/labs/lab11.adoc[Anti-debugging]

== 2021-10-28

Given the fact that the national holiday canceled one of our tutorials, we will need to make the following adjustments:

* Tutorial no. 6 (Malware lecture) is canceled. If you want to see it, please see the last year's recording, either in NIE-REV or in link:https://courses.fit.cvut.cz/BIE-BEK[BIE-BEK].
* Tutorial no. 7 (consultations) will take place in the 10th week (November 25).
* Tutorial no. 8 (simple obfuscations) will take place in the 7th week (November 4).
* Tutorial no. 9 (advanced obfuscations) will take place in the 8th week (November 11).
* Tutorial no. 10 (packed binaries) will take place in the 9th week (November 18).

Lectures and all other tutorials will take place on the previously scheduled dates. This change allows us to place tutorials to immediately follow their respective lectures, which is great -- usually, the tutorials are shifted by a week (or in the worse case, precede the lectures).

== 2021-09-11

The lectures and tutorials for Reverse engineering in this semester will be presented live. Should the epidemiological situation take a turn to the worse, we may have to switch to an online presentation using MS Teams; I will notify you of this change both here and using an e-mail sent from KOS.
