
= Current events: 2022-09-09
:toc:
:imagesdir: ../media

== 2022-09-09

The course materials were updated for the upcoming semester.

The lectures and tutorials for Reverse engineering in this semester will be presented live. Should the epidemiological and/or energetical situation take a turn to the worse, we may have to switch to an online presentation using MS Teams; I will notify you of this change both here and using an e-mail sent from KOS.

=== Important changes to the regular schedule

Basic facts:

* Due to important personal reasons, I am forced to cancel the tutorial on October 14th.
* Friday, October 28th, is a national holiday.
* Thursday, November 11th, is also a national holiday.
* Friday, November 18th, is the Dean's Day and the tutorial is moved to Tuesday, November 15th.

That means that we will lose one lecture and two tutorials. In order to minimize the damage, I decided to reorganize the tutorials in this way:

* We will cover tutorial 4 on Friday, October 21st.
* We will cover tutorial 5 on Friday, November 4th.
* We will cover tutorial 8 on Friday, November 11th.
* We will cover tutorial 9 on Tuesday, November 15th.

That means that we will lose tutorial 6 (which is not really a part of this course anymore as we moved it to the prerequisite course BIE-BEK) and tutorial 7 (which is intended for consultations anyway, with the remaining spaced filled with not-really-that-important exploration of how the concepts we observe during the course change in a 64bit environment), and the other tutorials will be slightly shifted around.

Furthermore, the national holiday of November 17th causes a desynchronization between the lectures and the tutorials -- lectures 5 and 6 will be delayed by two weeks which would affect the tutorials which depend on them. To fix that, we will exchange tutorials 11 and 13, that is:

* We will cover tutorial 13 on Friday 2nd.
* We will cover tutorial 11 on Friday 16th.

All the other days will be done as per usual.

I apologize for this overly complex rearrangement, but I couldn't figure out a better solution. You should find an easier-to-understand representation of the same thing xref:index.adoc#_schedule[in a table form] on the main page of the course.
