
= Evaluation
:toc:
:imagesdir: ../media

The evalution of the course consists of three parts -- evaluation of the homeworks (20 points), evaluation of the semestral works (20 and 30 points) and evaluation of the exam (30 points). The course is successfully completed by earning the assessment and by passing the exam.

== Assessment

The assessment is granted if the student gains a total of 35 or more points for homeworks and semestral works.

=== Homeworks

The homeworks are assigned during the tutorials. They consist of three tasks worth 5, 10 and 5 points, 20 points in total. The homeworks ask the student to explore important topics discussed during lectures and tutorials -- the understanding of the assembler code and basic control structures, the use of Import Address Table and the use of type information. *The solutions are to be submitted exclusively through e-mail. It is permitted to submit multiple solutions for each task* (e.g. in order to add missing parts or fix errors in the earlier submissions). A deadline has been set for each task, usually X weeks since the end of the tutorial where the task had been assigned (where X depends on the task); the submission e-mail must reach the teacher's mailbox by the deadline. Tasks submitted after the deadline *are not eligible for any points*, even if the task had been completed and the student only failed to deliver it. They may, however, be used to resolve borderline cases. A deadline may be individually delayed if serious reasons are proven.

In case of exceptional solutions the teacher may award bonus points in excess of standard values, depending on the quality of the solution. There points are solely in the province of the teacher, the student is not entitled to them.

In case of bugs in the submitted solutions the awarded points may be decreased, up to and including zero points in total for a given task. Please make use of the rather long submission deadlines and the possibility of resubmitting your solution to fix any discovered errors.

The list of homeworks and their deadlines can be found at the xref:index.adoc#_homework-deadlines[course's title page], here's just a list:

* xref:homeworks/email.adoc[E-mail] (5 pt.)
* xref:homeworks/iat.adoc[Import Table] (10 pt.)
* xref:homeworks/snake.adoc[Snake] (5 pt.)

=== Semestral works

The semestral works are focused on the actual reverse engineering of sample applications. Similar rules as for the homeworks apply, except that the deadline of each task is equal to the end of the exam period.

The solution of the semestral work should include a *very brief* description of the student's approach, the description of the structure of the application and its main principles, the description of the defense mechanisms used by the application, including the explanation of methods used by the student to overcome them. Note that the student must give suitable names to algorithms used by the application to hide key information -- in all cases the algorithms are well known and commonly used and the students should be familiar with them from their studies.

There are two semestral works, explained in detail at their respective pages:

* xref:projects/crackme.adoc[Crackme] (30+ points)
* xref:projects/keygen.adoc[Keygen] (20 points)

== The Exam

The course is concluded with an exam. *Only a student who has already been granted an assessment may take part in the exam.*

The content of the exam follows the information learned from lectures, tutorials and homeworks.

Each student can choose his or her preferred way of taking the exam, live or online. Please be aware that the grading criteria differ for each variant. There is also an option of concluding the course without undergoing an exam, as detailed below.

Completing the exam *does not* close the classification. The student may keep submitting more tasks until the end of the semester, as long as the task deadline wasn't reached yet.

=== Live Exam

The live exam is written, and takes 75 minutes. It may be supplemented with an oral examination in case of a suspicion of an unethical behavior.

During the exam, only writing utensils and a paper (provided by the teacher) may be used. No other tools are permitted. *It is expressly forbidden to use any kind of an electronic device at any time as long as the student is present in the exam room.*

The exam is worth 30 points. The minimum number of points required to get a grade better than "failed" is 15. There are 6 open questions in the exam, focused mostly (but not exclusively) on the theory. Each question is worth 5 points. An example exam is here: link:{imagesdir}/exam-en.pdf[Download].

=== Online Exam

An online exam is conducted in MS Teams in the form of a one-on-one voice chat; video is not required in order to protect the privacy of everyone. Before the exam, you will be given a time slot in which the chat will take place.

The online exam will take 20 minutes at most and will consist of questions from two topics from the course. In order to minimize attempts at cheating there will be no time provided for preparation, the answers should start immediately. The evaluation of the answers will be binary, "success" or "failure", rather than 0-30 points; in order to succeed in the exam, the student will need to provide at least a 50 % answer overall (i.e. if he or she fails completely in one question, they can still pass if they answer the second one perfectly). In case of a success, the student will be awarded points calculated as 3/7 of the points received from the homeworks.

If you submit more homeworks after you had completed the exam, your exam points will be recalculated according to the current amount of points from the homeworks.

[NOTE]
====
The reason for this difference in live and online exams is that I want to achieve the goals of the exam (to verify that the student understands the studied topics) while keeping the conditions as fair for all students as possible: In an online exam, it is not possible to prevent cheating and at the same time it is very difficult if not impossible to objectively rate the answers given. The binary rating can be done objectively and the point calculation prevents random fluctuations in the student's performance, both due to cheating and due to nervousness or stress. Two questions are asked to reduce the fear on part of the student that they may fail one of the questions completely.
====

Due to the popular demand, you may even choose to physically attend the online exam: You will sign up for a specific time slot and the exam will be conducted exactly as specified above, except that you won't actually connect to the exam through Teams but rather you will come physically to my office and we will complete the exam as a face-to-face chat rather than as a Teams voice-chat.

=== Concluding the Course Without an Exam

If a student achieves 50 or more points from the homeworks and the semestral works, he or she may opt to be excused from the exam, provided that he/she provably (using the school e-mail) requests so by the end of the third exam week (January 21nd, 2024) and hasn't taken part in any of the previous exam terms ("taking part" includes subscribing for an exam and then not coming). If the student is excused, he/she gets the grade given by the number of points from the homeworks and the semestral works and will not be allowed to take part in any other variant of the exam.

== Evaluation scale

Evaluation scale is according to the current link:https://fit.cvut.cz/en/studies/information-service/office-of-study-affairs/regulations[Study and Examination Code for Students of CTU in Prague] (link:https://www.cvut.cz/sites/default/files/content/74c76d2e-7f4d-4cb1-ac28-b0765c7f88f2/en/20221024-8th-full-text-of-the-study-and-examination-rules.pdf[PDF]).

[options="autowidth", cols=3*]
|====
<h| Grade
<h| Points
<h| Evaluation in words

| A
| 90 or more
| excellent

| B
| 80 to 89.999
| very good

| C
| 70 to 79.999
| good

| D
| 60 to 69.999
| satisfactory

| E
| 50 to 59.999
| sufficient

| F
| less than 50
| failed
|====
