
= Frequently Asked Questions
:toc:
:imagesdir: ./media

Here you can find answers to some common questions.

== Attendance

=== Do I have to attend the lectures?

Attendance to lectures is voluntary.The xref:recordings.adoc[recorded lectures] are a pretty good substitute, there are only minor changes. You will lose the ability to immediately ask about things you did not understand or are interested in more detail.

=== Do I have to attend the tutorials?

Attendance to tutorials is voluntary, but *highly* recommended. The xref:recordings.adoc[recorded tutorials] are not a sufficient substitute as the key part of the tutorials consists of trying to solve the puzzle and share your experience with your colleagues. While you can get by without attending the lectures, it will be difficult to complete the course without attending the tutorials.

=== Can I attend tutorial X if I am signed up for tutorial Y?

In the online form, YES.

In the live form, YES as long as there's room in the lab. If the lab's capacity is overfilled, the officially signed up students will be given preference.

In either case you don't need to inform me about the switch, send excuses etc. Just come when you will.

== Evaluation

=== Do I have to solve all tutorial tasks?

No. The tutorials are voluntary, both in attendance and in solving the tasks. You should be aware, though, that each tutorial and each task try to teach you something important about reverse engineering and you may encounter difficulties when trying to solve new tasks without finishing with the previous ones first.

=== Do I have to submit all homeworks?

No. The requirements to completing the course state that you need to get a certain amount of points. It's up to you where you find these points. If you solve the 6th password in Crackme, for example, you will get an A even if this was the only thing you did in this course.

=== Can I submit a partially completed homework?

Yes, and if you get stuck at something, it's the best thing to do -- I might help you get unstuck.

=== I have already done my exam, can I still submit the semestral works?

Yes. Every task has a deadline, but that's the only limiting factor for its submission. Whether you did or did not visit the exam is immaterial.

== Tools

=== Can I get the computer image from the lab?

Unfortunately, no. The image is based on the Microsoft Windows operating system which can't be legally copied in this way. The other tools can be downloaded from https://kib-files.fit.cvut.cz/mi-rev/nastroje/[here] or their homepages, but we are not allowed to distribute Windows.

You should definitely not abuse the administrative privileges you are given in the lab to surreptitiously create the images on your own.

=== Can I solve the tasks in Linux?

For the most part, yes --- a vast majority of the tools we are using either has a Linux version or can be run in Wine. You might encounter difficulties with a debugger, though, which would be a handicap in trying to solve tasks intended for dynamic analysis (tutorials 10 and 11 and the semestral work Crackme starting with the 3rd password).
