
= Evaluation
:toc:
:imagesdir: ../media

The evalution of the course consists of three parts -- evaluation of the homeworks (15 points), evaluation of the semestral works (20 and 35 points) and evaluation of the exam (30 points). The course is successfully completed by earning the assessment and by passing the exam.

== Assessment

The assessment is granted if the student gains a total of 30 or more points for homeworks and semestral works.

=== Homeworks

The homeworks are assigned during the tutorials. They consist of three tasks worth 5 points each, 15 points in total. The homeworks ask the student to explore important topics discussed during lectures and tutorials -- the understanding of the assembler code and basic control structures, the work with Import Address Table and the use of type information. *The solutions are to be submitted exclusively through e-mail. It is permitted to submit multiple solutions for each task* (e.g. in order to add missing parts or fix errors in the earlier submissions). A deadline has been set for each task, usually X weeks since the end of the tutorial where the task has been assigned (where X depends on the task); the submission e-mail must reach the teacher's mailbox by the deadline. Tasks submitted after the deadline *are not eligible for any points*, even if the task had been completed and the student only failed to deliver it. They may, however, be used to resolve borderline cases. A deadline may be individually delayed if serious reasons are proven.

In case of exceptional solutions the teacher may award bonus points in excess of standard values, depending on the quality of the solution. There points are solely in the province of the teacher, the student may not request them.

List of homeworks and their deadlines can be found at the xref:index.adoc[course's title page].

=== Semestral works

The semestral works are focused on the actual reverse engineering of sample applications. Similar rules as for the homeworks apply, except that the deadline of each task is equal to the end of the exam period.

The solution of the semestral work should include a *very brief* description of the student's approach, the description of the structure of the application and its main principles, the description of the defense mechanisms used by the application, including the explanation of methods used by the student to overcome them. Note that the student must give suitable names to algorithms used by the application to hide key information -- in all cases the algorithms are well known and commonly used and the students should be familiar with them from their studies.

There are two semestral works, explained in detail at their respective pages:

* xref:projects/crackme.adoc[Crackme] (35+ points)
* xref:projects/keygen.adoc[Keygen] (20 points)

== The Exam

The course is concluded with a written exam 75 minutes long, which may be supplemented with an oral examination in case of a suspicion of an unethical behavior. *Only a student who has already been granted an assessment may take part in the exam.*

During the exam, only writing utensils and a paper (provided by the teacher) may be used. No other tools are permitted. *It is expressly forbidden to use any kind of an electronic device at any time when the student is present in the exam room.*

The exam is worth 30 points. The minimum number of points required to get a grade better than "failed" is 15. The content of the exam follows the information learned from lectures, tutorials and homeworks. There are 6 open questions in the exam, focused mostly (but not exclusively) on the theory. Each question is worth 5 points.

If a student achieves 50 or more points from the homeworks and the semestral works, he or she may opt to be excused from the exam, provided that he/she provably (using the school e-mail) requests so by the end of the third exam week (January 24th, 2020) and hasn't taken part in any of the previous exam terms ("taking part" includes subscribing for an exam and then not coming). If the student is excused, he/she gets the grade given by the number of points from the homeworks and the semestral works.

Completing the exam does not close the classification. The student may keep submitting more tasks until the end of the semester, as long as the task deadline wasn't reached yet.

== Modifications for the Winter semester 2020/21

Due to the current epidemiological situation and its expected development, the following changes to the standard grading scheme will be applied to the Winter semester of 2020/21:

=== Assessment

The assessment parameters are not modified in any way.

=== Exam

At this moment, it is impossible to determine the properties of the exam exactly because it is not known how will the epidemiological situation evolve by the beginning of the exam period. I can, however, specify the possible alternatives as well as the criteria which will determine the selection of the final alternative.

[NOTE]
====
The reason why I chose these variants is that I need to satisfy the purpose of the exam (i.e. verification that the student understands the issues of reverse engineering and had not, for example, had the homeworks or semestral works done by a third party) as much as possible while doing my best at ensuring an equal opportunity for everyone (i.e. by preventing cheating), and at the same time eliminate as much of the subjective influences of the oral exams as possible.
====

==== Alternative 1

If it is, on January 4th, 2021, *not prohibited* (by the country, by CTU, or by FIT) to conduct personal meetings in the faculty's rooms, the exam will be performed in exactly the same fashion as usual.

==== Alternative 2

If it *is*, on January 4th, 2021, *prohibited*  (by the country, by CTU, or by FIT) to conduct personal meetings in the faculty's rooms, the exam will be modified in the following way. These modifications will be applied to all students without exception, regardless of any further developments of the epidemiological situation:

* The exam will be performed online in MS Teams and will be oral only. As far as technical requirements are concerned, you will only need an internet connection stable enough to hold throughout the exam and a microphone.

* The exam will take 10 minutes and will consist of one question. In order to minimize the risk of cheating, there won't be any preparatory period, the student will be expected to start answering straight away.

* The exam will not be evaluated by points but in a binary way -- either a "success" or a "failure". In case of a failure, the student will be graded F, as if he or she received zero points in the normal exam. In case of a success, the student will be awarded as many points as to maintain the percentage rate from the semester (in other words, the points from the semester will be multiplied by 3/7 and mathematically rounded to an integer number).

==== Alternative 3

If at least one exam according to Alternative 1 takes place and then the changes in the epidemiological situation force us to switch to Alternative 2, the students who succeeded in Alternative 1 will be given a choice whether they want to keep the points they received in their written exam or whether they want to have their points recalculated as if they had taken the Alternative-2 exam and succeeded.

Note that the change in the other direction will not happen. Once exams according to Alternative 2 start, there is no way back to Alternative 1 -- all future exams will be conducted according to Alternative 2 rules.

== Evaluation scale

Evaluation scale is according to the current https://www.cvut.cz/en/internal-ctu-regulations[Study and Examination Code for Students of CTU in Prague] (https://www.cvut.cz/sites/default/files/content/74c76d2e-7f4d-4cb1-ac28-b0765c7f88f2/en/20200624-study-and-examination-rules-for-students-of-ctu.pdf[PDF]).

[options="autowidth", cols=3*]
|====
<h| Grade
<h| Points
<h| Evaluation in words

| A
| 90 or more
| excellent

| B
| 80 to 89.999
| very good

| C
| 70 to 79.999
| good

| D
| 60 to 69.999
| satisfactory

| E
| 50 to 59.999
| sufficient

| F
| less than 50
| failed
|====
