
= NIE-REV Reverse Engineering
:toc:
:imagesdir: ../media

* xref:../index.adoc[Česká verze]

== Current events

Please keep an eye on the current events in the course on the xref:current_info.adoc[Current events] page.

== Annotation

Students will get acquainted with the essentials of reverse engineering of computer software. They will learn how processes start and what happens before and after the main function is called. Students will understand how executable files are organized and how they interact with 3rd party libraries. Another part of the course is dedicated to reverse engineering of applications written in C++. Students will also understand principles of disassemblers and obfuscation techniques. A part of the course will also be dedicated to debuggers: how debuggers and debugging work and which methods can be used to detect it. One of the lectures will be dedicated to the latest trends on the computer malware scene. The focus of the course is on the seminars, where students will solve practically oriented tasks from the real world.

== Teachers

*Josef Kokeš*

* E-mail: mailto:josef.kokes@fit.cvut.cz[josef.kokes@fit.cvut.cz]
* Office: TH:A-1137
* Consultations: As required, exact date and time to be determined through e-mail or personally at a lecture/tutorial.

== Note about the Winter semester 2020/21

Both lectures and tutorials for Reverse engineering will be presented physically in room T9:345 as per the regular timetable, at least in the beginning. While my personal preference in the current epidemiological situation is to keep all of my courses on-line to minimize risks (which is a recommended approach in Security after all), the small number of signed up students allows me to follow the faculty's recommendation to conduct the english-language courses in person rather than online. It remains to be seen how long will this approach remain viable.

Note that this *will* be changed if the number of signed-up students exceeds 12.

== Evaluation

* xref:evaluation.adoc[Requirements for passing the course]
* The points awarded will be recorded at the https://grades.fit.cvut.cz[FIT grades] website. In your own interest, verify that you got the correct amount of points every time you get an e-mail from me. The points shown at Grades are just "for your information", the definitive value is in my private "master" list.

=== Homework deadlines

[options="autowidth", cols=4*]
|====
<h| Task
<h| Points
<h| Assigned
<h| Deadline

| xref:homeworks/email.adoc[E-mail]
| 5
| 3rd week
| November 4, 19:30

| xref:homeworks/iat.adoc[IAT]
| 10
| 4th week
| November 18, 19:30

| xref:homeworks/snake.adoc[Snake]
| 10
| 5th week
| December 9, 19:30

| xref:projects/crackme.adoc[Crackme]
| 25+
| 3rd week
| February 14, 8:00

| xref:projects/keygen.adoc[Keygen]
| 20
| 1st week
| February 13, 8:00

| xref:labs/lab13.adoc[Bonus]
| 3
| 13th week
| February 13, 8:00
|====

== Changes to the schedule

None specified yet.

////
* *6th tutorial* (xref:labs/lab06.adoc[Martin Jirkal's lecture on malware]) is postponed until November 20. It's unclear whether it will be presented by Mr. Jirkal or by myself, it depends on the then-current situation.
* *7th tutorial* (xref:labs/lab07.adoc[consultations + 64bit code]) is moved ahead to the 6th week (October 30).
* *8th tutorial* (xref:labs/lab08.adoc[simple obfuscations]) is moved ahead to the 7th week (November 6).
* *9th tutorial* (xref:labs/lab09.adoc[advanced obfuscations]) is moved ahead to the 7th week (November 13).
* On November 20, we had a consultation tutorial with even more deobfuscation work. The *10th tutorial* (unpacking) will be done on November 27.
* On December 4th, we will have the *6th lecture* (debugging and antidebugging) and the *11th tutorial* (also debugging and antidebugging).
* On December 11th, we will have the *13th tutorial* (injection).
* On December 18th, *Martin Jirkal from ESET* will give a lecture on malware. The topic of the tutorial, if any, is undecided as yet; if Mr. Jirkal is willing, perhaps he could demonstrate reverse engineering of high-level languages such as dotnet. Or we can end early and enjoy the Christmas instead of reverse engineering :-).

* *2019-11-07 (week 7)*:
** In place of the *disassembling and obfuscation* lecture Ing. Martin Jirkal from ESET will present a lecture on *malware* (regularly lecture no.7).
** In place of the *malware* tutorial we will have the *consultations and 64bit code* tutorial (regularly tutorial no.7).
* *2019-11-14 (week 8)*:
** In place of the *consultations and 64bit code* tutorial we will have a lecture on *disassembling and obfuscation* (regularly lecture no.4).
* *2019-12-12 (week 12)*:
** Ing. Martin Jirkal will present a tutorial on *dotnet analysis* (in Czech).
* *2019-12-19 (week 13)*:
** Ing. Jan Rubín from Avast will present a lecture on *malware analysis* (in Czech).
** link:{imagesdir}/lectures/rev08en.pdf[Slides].
** link:{imagesdir}/itsaunixsystem.zip[Crackme to try out].
////

== Downloads

Offline version of these pages is available here: https://kib-files.fit.cvut.cz/mi-rev/offline.zip[Download]

Tools used in tutorials can be downloaded here: https://kib-files.fit.cvut.cz/mi-rev/nastroje/[Download]

Runtime libraries for various versions of Visual Studio can be downloaded here: https://kib-files.fit.cvut.cz/mi-rev/vcredist/[Download]

//Úvodní přednášky a cvičení z BI-BEK, kde si vysvětlujeme základy assembleru, naleznete zde: https://kib-files.fit.cvut.cz/bi-bek/BIK01-prednasky_1_2_cviceni_1_2.mp4[Download]
