
= Assignment of semestral works
:toc:
:imagesdir: ../media

* Points: *35+*
* Deadline: *unlimited* (caveat below)

== Requirements

Your goal is to analyze your assigned program and find a series of passwords required to pass through the application. There are four (resp. six) passwords, each giving you access to further passwords. Some passwords are generated differently for each student. The program uses a steadily increasing number of anti-reversing techniques which prevent a fast analysis.

Write a *brief* report which will cover these questions for each stage of the application:

* Which password will let us move to the next stage?
* How do we enter this password?
* Which protections are used by the application? If standard algorithms are used, name them!
* How does the application hide its functionality?
* What was your approach to finding the password?

Because partial submissions are permitted, it's necessary that the report contains sufficient information to allow the teacher to determine how far did you progress and to award you respective points. On the other hand, you don't need to create interesting characters and a gripping plot, it's perfectly fine to submit a bullet list. We are much more interested in the information found than the presentation.


[IMPORTANT]
====
A solution which does not work with the original unchanged application will not be accepted! You may modify the program to facilitate your analysis, but the correctness of the solution will be verified using the original program!
====

Please send your solutions to your tutorials teacher using e-mail.

== Deadline

Solutions may be submitted until the end of the exam period. However, make allowances for the fact that it takes some time to verify your solution and plan your submissions as to provide a sufficient time between the submission and the deadline of the exam. If you submit your work at least a week (168 hours) before the beginning of an exam, you are guaranteed to be able to attend that exam.

== Grading scheme

* *Password 1* -- a simple fixed password. *5 points*
* *Password 2* -- a generated random password, simple obfuscations, requires extraction into memory. *10 points*
* *Password 3* -- a simple password in a new packed executable, moderate difficulty. *10 points*
* *Password 4* -- a generated random password, strong obfuscations, needed for a full score. *10 points*
* Password 5 -- a bonus password, well hidden, serves as a partial alternative to the "Keygen" work. *10 points*
* Password 6 -- a bonus password, extreme obfuscations (a dedicated virtual machine), not expected to be solved -- serves as an example of what you could encounter in the real world. *100 points*

Partial solutions are possible. The points shown above denote the maximum amount of points you can get for that part of the work.

== Assignment of semestral works to students

Please solve only "your" assigment, solutions of other people's assignments will be ignored (except for possible penalties for cheating). The solution should be your own work for the most part -- consulations are possible, even in real world, but you will find it difficult to find someone to do the work for you all the time.

The assignments will be provided during the third week of the semester.
