
= Aktuality: 09.12.2021
:toc:
:imagesdir: ./media

== 09.12.2021

Bohužel, podle očekávání musíme zrušit původně plánovanou formu cvičení 12 kvůli nemoci přednášejícího. Pokusím se ho zastoupit a ukázat aspoň základy, obávám se však, že to nebude příliš dobré, protože Dotnet skutečně není mojí specializací. Omluvte proto prosím sníženou kvalitu cvičení. Jinak samozřejmě budu k dispozici pro případné otázky, a to jak prezenčně v laboratoři, tak online.

== 06.12.2021

Martin Jirkal, který měl tento týden demonstrovat analýzu vysokoúrovňových jazyků, bohužel onemocněl Covidem, což znamená, že demonstrace zcela určitě nebude moci být provedena v živé podobě. Pokud bude vůbec možné ji letos realizovat, bude to pouze v online podobě. Jistější informace budu mít ve středu večer nebo ve čtvrtek ráno.

Pokud by se cvičení konat nemohlo, chovejte se k němu prosím, jako kdyby odpadlo. Zájemci o analýzu vyšších jazyků mohou využít https://kib-files.fit.cvut.cz/mi-rev/MIE-tutorial_12.mp4[nahrávky], kterou jsme vytvořili předloni pro anglickou verzi předmětu. Abyste však nebyli o cvičení úplně ochuzeni, budu dostupný jak online tak fyzicky v laboratoři, ale není plánovaný žádný konkrétní program -- cvičení bude ryze konzultační.

== 25.11.2021

Vypsal jsem v KOSu předtermíny prezenční zkoušky. Pro účast je požadován zápočet.

== 21.11.2021

Připomínám (raději i sobě), že 2.12. nebude přednáška na debugování a antidebugování, ale přednáška Jana Rubína z firmy Avast o analýze malwaru s ukázkou. Přednáška na debugging bude až o dva týdny později, 16.12. V důsledku toho se jeví jako vhodné prohodit cvičení 11 a 13 tak, abyste nemuseli řešit úlohu na antidebugging předtím, než se dozvíte, jak vlastně antidebugging funguje. Souhrnně tedy:

* 2.12.
** Přednáška: **Analýza malware** (Jan Rubín, Avast). Pozor, přednáška se **nebude** ani streamovat ani nahrávat, bude pouze prezenční. Doporučuji nicméně na ni přijít, pokud to bude jen trochu možné, stojí za to.
** Cvičení: xref:{imagesdir}/../labs/lab13.adoc[Injekce kódu]
* 9.12.
** Cvičení: xref:{imagesdir}/../labs/lab12.adoc[Analýza .NET] (Martin Jirkal, ESET)
* 16.12.
** Přednáška: xref:{imagesdir}/lectures/rev06cz.pdf[Debugging a anti-debugging]
** Cvičení: xref:{imagesdir}/../labs/lab11.adoc[Anti-debugging]

(Páteční cvičení budou pochopitelně o den později, než je uvedeno výše.)

== 28.10.2021

S ohledem na proběhlý státní svátek a děkanský den, které nás připravily o jedno cvičení, ale zase nám více sblížily přednášky s cvičeními, proběhnou následující přesuny:

* Cvičení č. 6 (přednáška Malware) odpadá. Můžete využít nahrávky z loňska, jak v předmětu NI-REV, tak v předmětu https://courses.fit.cvut.cz/BI-BEK[BI-BEK].
* Cvičení č. 7 (konzultace) proběhne v 10. týdnu (25.-26.11.).
* Cvičení č. 8 (jednoduché obfuskace) proběhne v 7. týdnu (4.-5.11.).
* Cvičení č. 9 (složitější obfuskace) proběhne v 8. týdnu (11.-12.11.).
* Cvičení č. 10 (pakované binárky) proběhne v 9. týdnu (18.-19.11.).

Přednášky a také všechna ostatní cvičení proběhnou v původně naplánovaných časech. Výhodou tohoto přesunu je, že budeme moci ihned po příslušné přednášce navázat příslušným cvičením, zatímco normálně by cvičení bylo o týden posunuté.

== 11.9.2021

Výuka předmětu Reverzní inženýrství v zimním semestru 2021/22 by měla dle aktuálních informací probíhat živě. Pokud dojde ke zhoršení epidemiologické situace, může dojít k přesunu výuky do online prostředí MS Teams; v tom případě o této změně budu informovat na této stránce a také pomocí e-mailu z KOSu.
