
= Aktuality: 30.11.2023
:toc:
:imagesdir: ./media

== 30.11.2023

Materiály pro pondělní přednášku Jana Rubína:

* link:{imagesdir}/lectures/rev08en.pdf[Přednáška]
* link:{imagesdir}/itsaunixsystem.zip[Crackme na vyzkoušení]

== 08.10.2023

xref:projects/crackme.adoc[Zadání úlohy Crackme] byla přiřazena studentům. Prosím, ověřte si, že můžete stáhnout a rozbalit své zadání; v případě problémů mě prosím kontaktujte, abych to mohl opravit a úlohu vám zpřístupnit.

== 20.09.2023

Všechny externí přednášející mám potvrzené, časový rozpis přednášek a cvičení by tak měl být finální (nedojde-li k žádným neobvyklým situacím).

Prosím, počítejte s tím, že přednáška Jana Rubína (4.12.2023) bude téměř jistě pouze prezenční, tedy nebude ani streamována, ani nahrávána. Vyhraďte si pro ni čas na osobní přítomnost, stojí to za to.

== 09.09.2023

Výukové materiály aktualizovány pro nadcházející semestr.

Tyto aspekty zatím nejsou v definitivní podobě a nejspíš se budou měnit, chci ale publikovat ostatní předpokládané materiály co nejdříve, abyste se na ně mohli připravit:

- Zatím není potvrzen termín xref:labs/lab12.adoc[cvičení 12 s Martinem Jirkalem].
- V xref:projects/keygen.adoc[semestrální práci Keygen] se s největší pravděpodobností bude měnit zkoumaná binárka tak, aby netrpěla problémy s kompatibilitou jako ta současná.
