
= Aktuality: 20.09.2022
:toc:
:imagesdir: ./media

== 20.09.2022

Oba externí přednášející potvrdili svoji účast. Můžete se tedy těšit na povídání o reverzní analýze vysokoúrovňového kódu na cvičeních od Martina Jirkala (ESET) ve 12. týdnu (8. a 9.12.) a na praktickou demonstraci uplatnění reverzního inženýrství při analýze malware od Jana Rubína (Avast) na přednášce ve 13. týdnu (15.12.).

Speciálně upozorňuji, že Jan Rubín si nepřeje nahrávání a přednáška tedy bude provedena **pouze prezenčně**. Prosím, vyhraďte si na ni čas, stojí to za to.

Aby se nám obě přednášky do předmětu vešly, musel jsem udělat následující přesuny:

* Šestá přednáška (debugging a antidebugging) proběhne na cvičení v 11. týdnu.
* Třinácté cvičení (injekce) se ruší. Nicméně zájemci o splnění jeho bonusové úlohy si ho mohou pustit ze záznamu.

== 09.09.2022

Stránky předmětu byly aktualizovány pro nadcházející semestr.

Výuka předmětu Reverzní inženýrství v zimním semestru 2021/22 by měla dle aktuálních informací probíhat živě. Pokud dojde ke zhoršení epidemiologické a/nebo energetické situace, může dojít k přesunu výuky do online prostředí MS Teams; v tom případě o této změně budu informovat na této stránce a také pomocí e-mailu z KOSu.

=== Důležité změny proti standardnímu harmonogramu:

Základní fakta:

* Z důležitých osobních důvodů bohužel musím zrušit výuku v pátek 14.10.
* V pátek 28.10. je státní svátek.
* Ve čtvrtek 17.11. je také státní svátek.
* V pátek 18.11. je děkanský den, výuka se přesouvá na úterý 15.11.

To pro nás znamená ztrátu jedné přednášky a dvou cvičení. Pro minimalizaci škod a zajištění maximální kompatibility mezi cvičeními jsem se rozhodl toto vyřešit následujícím způsobem:

* Ve čtvrtek 13.10. provedeme cvičení 7.
* Ve čtvrtek 20.10. a v pátek 21.10. provedeme cvičení 4.
* Ve čtvrtek 27.10. provedeme cvičení 8 pro paralelku 101.
* Ve čtvrtek 03.11. a v pátek 04.11. provedeme cvičení 5.
* Ve čtvrtek 10.11. provedeme cvičení 9 pro paralelku 101.
* V pátek 11.11. provedeme cvičení 8 pro paralelky 102 a 103.
* V úterý 15.11. provedeme cvičení 9 pro paralelky 102 a 103.

To znamená, že ve výsledku odpadne cvičení 6 (které už stejně bylo přesunuto do předmětu BI-BEK) a pro velkou část z vás cvičení 7 (které je tak jako tak z větší části míněno jako konzultační a zbývající čas je vyplněn vcelku okrajovou problematikou toho, jak by mohl vypadat 64bitový kód) a ostatní cvičení se posunou.

Dále potřebujeme opravit desynchronizaci přednášek a cvičení kvůli tomu, že nám přednáška 17.11. odpadne a tím dojde k posunu přednášek 5 a 6 vůči odpovídajícím cvičením. To vyřešíme tak, že prohodíme cvičení 11 a 13, tedy:

* Ve čtvrtek 01.12. a v pátek 02.12. provedeme přednášku 5 a cvičení 13.
* Ve čtvrtek 15.12. a v pátek 16.12. provedeme přednášku 6 a cvičení 11.

Ostatní dny proběhnou normálně.

Omlouvám se za komplexitu, ale lepší řešení mě nenapadlo. Na hlavní stránce předmětu je totéž snad vyjádřeno přehledněji xref:index.adoc#_pl%C3%A1n-v%C3%BDuky[v podobě tabulky].
