
= Hodnocení
:toc:
:imagesdir: ./media

Hodnocení předmětu se skládá ze tří částí -- hodnocení domácích úloh (20 bodů), hodnocení semestrálních prací (20 a 30 bodů) a hodnocení zkoušky (30 bodů). Předmět je řádně ukončen získáním zápočtu a složením zkoušky.

== Zápočet

Zápočet student získá v případě, že dosáhne nejméně 35 bodů z domácích úloh a semestrálních prací.

=== Domácí úlohy

Domácí úlohy jsou zadávány na cvičeních a jsou tvořeny třemi úlohami za 5, 10 a 5 bodů, celkem tedy až 20 bodů. Úlohy se zabývají dílčími oblastmi probíranými na přednáškách a cvičeních -- porozumění assemblerovému kódu a základních řídících struktur, práce s Import Address Table a využití typové informace. *Úlohy se odevzdávají zásadně e-mailem cvičícímu a je přípustné i několikanásobné odevzdání* (např. pro doplnění chybějících částí nebo opravu chyb). Pro každou domácí úlohu je stanoven samostatný termín, ve kterém musí být odevzdána, standardně X týdnů od konce cvičení, na kterém byla úloha zadána (X se liší podle úlohy); rozhodným okamžikem je čas doručení zprávy do e-mailové schránky cvičícího. Úlohy odevzdané po uplynutí termínu *budou hodnoceny 0 body*, a to i v případě, že úloha vypracována byla a jen se ji nepodařilo včas doručit. Mohou však být využity pro rozhodnutí sporných případů. V případě doložených vážných důvodů může být termín stanoven individuálně.

V případě mimořádně kvalitního řešení může cvičící přiznat studentovi bonusové body nad rámec stanovených limitů, dle kvality řešení. Na tyto body není nárok, jsou zcela v pravomoci cvičícího.

V případě výskytu chyb v řešení může být hodnocení sníženo, a to dle množství a závažnosti chyb až na nula bodů za danou úlohu. Využijte poměrně dlouhou lhůtu na vypracování a možnost opakovaného odevzdání k opravení vytčených chyb!

Seznam úloh a jejich deadline je uveden na xref:index.adoc#_term%C3%ADny-odevzd%C3%A1n%C3%AD-%C3%BAloh[hlavní stránce předmětu], zde jen rychlý přehled:

* xref:homeworks/email.adoc[E-mail] (5 b.)
* xref:homeworks/iat.adoc[Importní tabulka] (10 b.)
* xref:homeworks/snake.adoc[Had] (5 b.)

=== Semestrální práce

Semestrální práce se zabývají reverzním inženýrstvím rozsáhlejších programů. Platí pro ně obdobná pravidla jako pro domácí úlohy s tím rozdílem, že termínem pro odevzdání je konec zkouškového období.

Výsledkem semestrální práce by měl být *velmi stručný* popis vašeho postupu, popis hrubé struktury analyzovaného programu a jeho základních principů, popis obranných mechanismů, které program používá, včetně vysvětlení, jak je student překonával(a). Velmi důležité je také pojmenování algoritmů, které program používá pro skrytí klíčových informací -- ve všech případech jde o známé a běžně používané algoritmy, které byste určitě měli z dřívějšího studia znát.

Semestrální práce jsou celkem dvě a jsou detailně popsané na samostatných stránkách:

* xref:projects/crackme.adoc[Crackme] (30+ bodů)
* xref:projects/keygen.adoc[Keygen] (20 bodů)

== Zkouška

Předmět je standardně zakončen zkouškou. *Zúčastnit se jí může pouze student, který už má zapsaný zápočet.*

Obsahově zkouška odpovídá látce z přednášek, cvičení i domácích úloh.

Student si může zvolit, zda chce složit zkoušku prezenčně (preferovaný způsob) nebo distančně. Pozor, každá varianta má jiné hodnocení, které mimo jiné reflektuje spolehlivost daného způsobu zkoušení. Existuje i možnost zakončit předmět bez zkoušky za podmínek popsaných níže.

Složením zkoušky se *neuzavírá* klasifikace, student může až do konce semestru odevzdávat úlohy, jimž dosud neuplynul deadline.

=== Prezenční zkouška

Prezenční zkouška je písemná, v délce 75 minut, v případě podezření z neetického chování může být doplněna ústním dozkoušením. 

Při zkoušce je povoleno používat pouze psací potřeby a dále papír přidělený zkoušejícím. Žádné jiné pomůcky nejsou povoleny. *Výslovně je zakázáno použití jakýchkoliv elektronických zařízení, a to po celou dobu pobytu studenta ve zkouškové místnosti.*

Ze zkoušky lze získat až 30 bodů. Minimum pro získání známky jiné než "nedostatečně" je 15 bodů. Je tvořena šesti otevřenými otázkami zaměřenými zejména (ale ne výhradně) na teorii. Každá otázka je hodnocena 5 body. Příklad zkouškové písemky je zde: link:{imagesdir}/exam-cz.pdf[Download].

=== Distanční zkouška

Distanční zkouška se koná online v prostředí MS Teams jako hlasový hovor dvou osob (zkoušející a zkoušený); obraz není z důvodu ochrany soukromí vyžadován. S předstihem budou přiděleny časové sloty, ve kterých se bude hovor konat.

Online zkouška potrvá max. 20 minut a budou v ní zkoumány dva okruhy z probrané látky. Z důvodu minimalizace rizika podvodů nebude povolen čas na přípravu. Hodnocení zkoušky nebude stanoveno v podobě bodů ale pouze binárně jako "úspěch" nebo "neúspěch"; pro úspěch musí student otázky zodpovědět aspoň z poloviny dohromady (tedy i naprostý neúspěch u jedné otázky je možné kompenzovat vynikajícím výkonem u otázky druhé). V případě úspěšného složení zkoušky dostane student přiděleny body spočítané koeficientem z bodů získaných v rámci zápočtu (tzn. za zkoušku student získá 3/7 bodů, které získal z úloh).

Pokud po složení zkoušky doodevzdáte další úlohy, budou body ze zkoušky přepočítány podle aktuálního stavu bodů ze zápočtu.

[NOTE]
====
Důvodem pro takto stanovené hodnocení je snaha zajistit v maximální možné míře dosažení účelu zkoušky (tzn. ověření, že student rozumí probrané problematice) při dodržení co nejspravedlivějších podmínek pro všechny: Při distanční zkoušce není možné na jedné straně zamezit pokusům o podvádění a na druhé straně objektivně a přezkoumatelně ohodnotit kvalitu odpovědi. Binární hodnocení lze rozhodnout dosti objektivně a přepočet bodů ze semestru spolu s relativně malým podílem bodů ze zkoušky na celkovém hodnocení eliminuje příliš velké výkyvy, ať už způsobené podvodem nebo např. nervozitou či nezvykem na tento způsob zkoušení. Od dvou otázek si pak slibuji snížení stresu plynoucího z obav, že student zrovna tu jednu položenou otázku nebude vůbec znát.
====

Na četné žádosti bude umožněna i varianta distanční zkoušky, na kterou se nebudete připojovat přes Teams, ale fyzicky. Přihlašujete se stále na konkrétní časový termín a v něm proběhne zkouška přesně podle parametrů uvedených výše, ale máte možnost přijít na něj osobně do kanceláře a zkouška proběhne formou face-to-face hovoru namísto voice-chatu.

=== Zakončení předmětu bez zkoušky

Získá-li student z domácích úloh a semestrálních prací celkem 50 nebo více bodů, může mu být zkouška prominuta, pokud o to prokazatelně (školním e-mailem) požádá zkoušejícího nejpozději do konce 3. týdne zkouškového období (22.1.2023) a současně se žádného zkouškového termínu nezúčastnil (účastí se rozumí i nedostavení se na zkoušku, na kterou byl student přihlášen). Prominutím zkoušky student získá známku odpovídající počtu bodů dosažených z domácích úloh a semestrálních prací. Zároveň tím ztrácí možnost zúčastnit se jiné varianty zkoušky.

== Celkové hodnocení

Hodnocení se řídí aktuálním link:https://www.cvut.cz/vnitrni-predpisy[Studijním a zkušebním řádem ČVUT] ( link:https://www.cvut.cz/sites/default/files/content/74c76d2e-7f4d-4cb1-ac28-b0765c7f88f2/cs/20211023-studijni-a-zkusebni-rad-pro-studenty-cvut-v-praze-iv-uplne-zneni-ucinnost-od-20-9-2021.pdf[PDF] ).

[options="autowidth", cols=3*]
|====
<h| Známka
<h| Bodové +
rozmezí
<h| Slovní +
hodnocení

| A
| 90 a více
| výborně

| B
| 80 až 89,999
| velmi dobře

| C
| 70 až 79,999
| dobře

| D
| 60 až 69,999
| uspokojivě

| E
| 50 až 59,999
| dostatečně

| F
| méně než 50
| nedostatečně
|====
