
= Hodnocení
:toc:
:imagesdir: ./media

Hodnocení předmětu se skládá ze tří částí -- hodnocení domácích úloh (15 bodů), hodnocení semestrálních prací (20 a 35 bodů) a hodnocení zkoušky (30 bodů). Předmět je řádně ukončen získáním zápočtu a složením zkoušky.

== Zápočet

Zápočet student získá v případě, že dosáhne nejméně 30 bodů z domácích úloh a semestrálních prací.

=== Domácí úlohy

Domácí úlohy jsou zadávány na cvičeních a jsou tvořeny třemi úlohami po 5 bodech, celkem tedy až 15 bodů. Úlohy se zabývají dílčími oblastmi probíranými na přednáškách a cvičeních -- porozumění assemblerovému kódu a základních řídících struktur, práce s Import Address Table a využití typové informace. *Úlohy se odevzdávají zásadně e-mailem cvičícímu a je přípustné i několikanásobné odevzdání* (např. pro doplnění chybějících částí nebo opravu chyb). Pro každou domácí úlohu je stanoven samostatný termín, ve kterém musí být odevzdána, standardně X týdnů od konce cvičení, na kterém byla úloha zadána (X se liší podle úlohy); rozhodným okamžikem je čas doručení zprávy do e-mailové schránky cvičícího. Úlohy odevzdané po uplynutí termínu *budou hodnoceny 0 body*, a to i v případě, že úloha vypracována byla a jen se ji nepodařilo včas doručit. Mohou však být využity pro rozhodnutí sporných případů. V případě doložených vážných důvodů může být termín stanoven individuálně.

V případě mimořádně kvalitního řešení může cvičící přiznat studentovi bonusové body nad rámec stanovených limitů, dle kvality řešení. Na tyto body není nárok, jsou zcela v pravomoci cvičícího.

Seznam úloh a jejich deadline je uveden na xref:index.adoc[hlavní stránce předmětu].

=== Semestrální práce

Semestrální práce se zabývají reverzním inženýrstvím existujících programů. Platí pro ně obdobná pravidla jako pro domácí úlohy s tím rozdílem, že termínem pro odevzdání je konec zkouškového období.

Výsledkem semestrální práce by měl být *velmi stručný* popis vašeho postupu, popis hrubé struktury analyzovaného programu a jeho základních principů, popis obranných mechanismů, které program používá, včetně vysvětlení, jak je student překonával(a). Velmi důležité je také pojmenování algoritmů, které program používá pro skrytí klíčových informací -- ve všech případech jde o známé a běžně používané algoritmy, které byste určitě měli z dřívějšího studia znát.

Semestrální práce jsou celkem dvě a jsou detailně popsané na samostatných stránkách:

* xref:projects/crackme.adoc[Crackme] (35+ bodů)
* xref:projects/keygen.adoc[Keygen] (20 bodů)

== Zkouška

Předmět je standardně zakončen zkouškou. Ta je písemná, v délce 75 minut, v případě podezření z neetického chování může být doplněna ústním dozkoušením. *Zúčastnit se zkoušky může pouze student, který už má zapsaný zápočet.*

Při zkoušce je povoleno používat pouze psací potřeby a dále papír přidělený zkoušejícím. Žádné jiné pomůcky nejsou povoleny. *Výslovně je zakázáno použití jakýchkoliv elektronických zařízení, a to po celou dobu pobytu studenta ve zkouškové místnosti.*

Ze zkoušky lze získat až 30 bodů. Minimum pro získání známky jiné než "nedostatečně" je 15 bodů. Obsahově zkouška odpovídá látce z přednášek, cvičení i domácích úloh. Je tvořena šesti otevřenými otázkami zaměřenými zejména (ale ne výhradně) na teorii. Každá otázka je hodnocena 5 body.

Získá-li student z domácích úloh a semestrálních prací celkem 50 nebo více bodů, může mu být zkouška prominuta, pokud o to prokazatelně (školním e-mailem) požádá zkoušejícího nejpozději do konce 3. týdne zkouškového období (24.1.2020) a současně se žádného zkouškového termínu nezúčastnil (účastí se rozumí i nedostavení se na zkoušku, na kterou byl student přihlášen). Prominutím zkoušky student získá známku odpovídající počtu bodů dosažených z domácích úloh a semestrálních prací.

Složením zkoušky se *neuzavírá* klasifikace, student může až do konce semestru odevzdávat úlohy, jimž dosud neuplynul deadline.

== Celkové hodnocení

Hodnocení se řídí aktuálním https://www.cvut.cz/vnitrni-predpisy[Studijním a zkušebním řádem ČVUT] ( https://www.cvut.cz/sites/default/files/content/74c76d2e-7f4d-4cb1-ac28-b0765c7f88f2/cs/20200624-studijni-a-zkusebni-rad-pro-studenty-cvut-v-praze-iii-uplne-zneni-ucinnost-od-11-3-2020_0.pdf[PDF] ).

[options="autowidth", cols=3*]
|====
<h| Známka
<h| Bodové +
rozmezí
<h| Slovní +
hodnocení

| A
| 90 a více
| výborně

| B
| 80 až 89.999
| velmi dobře

| C
| 70 až 79.999
| dobře

| D
| 60 až 69.999
| uspokojivě

| E
| 50 až 59.999
| dostatečně

| F
| méně než 50
| nedostatečně
|====
