
= Hodnocení
:toc:
:imagesdir: ./media

Hodnocení předmětu se skládá ze tří částí -- hodnocení domácích úloh (15 bodů), hodnocení semestrálních prací (20 a 35 bodů) a hodnocení zkoušky (30 bodů). Předmět je řádně ukončen získáním zápočtu a složením zkoušky.

== Zápočet

Zápočet student získá v případě, že dosáhne nejméně 30 bodů z domácích úloh a semestrálních prací.

=== Domácí úlohy

Domácí úlohy jsou zadávány na cvičeních a jsou tvořeny třemi úlohami po 5 bodech, celkem tedy až 15 bodů. Úlohy se zabývají dílčími oblastmi probíranými na přednáškách a cvičeních -- porozumění assemblerovému kódu a základních řídících struktur, práce s Import Address Table a využití typové informace. *Úlohy se odevzdávají zásadně e-mailem cvičícímu a je přípustné i několikanásobné odevzdání* (např. pro doplnění chybějících částí nebo opravu chyb). Pro každou domácí úlohu je stanoven samostatný termín, ve kterém musí být odevzdána, standardně X týdnů od konce cvičení, na kterém byla úloha zadána (X se liší podle úlohy); rozhodným okamžikem je čas doručení zprávy do e-mailové schránky cvičícího. Úlohy odevzdané po uplynutí termínu *budou hodnoceny 0 body*, a to i v případě, že úloha vypracována byla a jen se ji nepodařilo včas doručit. Mohou však být využity pro rozhodnutí sporných případů. V případě doložených vážných důvodů může být termín stanoven individuálně.

V případě mimořádně kvalitního řešení může cvičící přiznat studentovi bonusové body nad rámec stanovených limitů, dle kvality řešení. Na tyto body není nárok, jsou zcela v pravomoci cvičícího.

Seznam úloh a jejich deadline je uveden na xref:index.adoc[hlavní stránce předmětu].

=== Semestrální práce

Semestrální práce se zabývají reverzním inženýrstvím existujících programů. Platí pro ně obdobná pravidla jako pro domácí úlohy s tím rozdílem, že termínem pro odevzdání je konec zkouškového období.

Výsledkem semestrální práce by měl být *velmi stručný* popis vašeho postupu, popis hrubé struktury analyzovaného programu a jeho základních principů, popis obranných mechanismů, které program používá, včetně vysvětlení, jak je student překonával(a). Velmi důležité je také pojmenování algoritmů, které program používá pro skrytí klíčových informací -- ve všech případech jde o známé a běžně používané algoritmy, které byste určitě měli z dřívějšího studia znát.

Semestrální práce jsou celkem dvě a jsou detailně popsané na samostatných stránkách:

* xref:projects/crackme.adoc[Crackme] (35+ bodů)
* xref:projects/keygen.adoc[Keygen] (20 bodů)

== Zkouška

Předmět je standardně zakončen zkouškou. Ta je písemná, v délce 75 minut, v případě podezření z neetického chování může být doplněna ústním dozkoušením. *Zúčastnit se zkoušky může pouze student, který už má zapsaný zápočet.*

Při zkoušce je povoleno používat pouze psací potřeby a dále papír přidělený zkoušejícím. Žádné jiné pomůcky nejsou povoleny. *Výslovně je zakázáno použití jakýchkoliv elektronických zařízení, a to po celou dobu pobytu studenta ve zkouškové místnosti.*

Ze zkoušky lze získat až 30 bodů. Minimum pro získání známky jiné než "nedostatečně" je 15 bodů. Obsahově zkouška odpovídá látce z přednášek, cvičení i domácích úloh. Je tvořena šesti otevřenými otázkami zaměřenými zejména (ale ne výhradně) na teorii. Každá otázka je hodnocena 5 body.

Získá-li student z domácích úloh a semestrálních prací celkem 50 nebo více bodů, může mu být zkouška prominuta, pokud o to prokazatelně (školním e-mailem) požádá zkoušejícího nejpozději do konce 3. týdne zkouškového období (24.1.2021) a současně se žádného zkouškového termínu nezúčastnil (účastí se rozumí i nedostavení se na zkoušku, na kterou byl student přihlášen). Prominutím zkoušky student získá známku odpovídající počtu bodů dosažených z domácích úloh a semestrálních prací.

Složením zkoušky se *neuzavírá* klasifikace, student může až do konce semestru odevzdávat úlohy, jimž dosud neuplynul deadline.

== Úpravy pro zimní semestr 2020/21

V důsledku současné epidemiologické situace a jejího očekávaného vývoje stanovuji následující úpravy parametrů hodnocení pro zimní semestr 2020/21:

=== Zápočet

Parametry zápočtu se nemění.

=== Zkouška

V tuto chvíli nelze přesně určit, jak bude zkouška probíhat, protože není známo, jaká bude epidemiologická situace v průběhu zkouškového období. Jsou ale dopředu stanoveny následující varianty včetně kritérií, podle kterých bude konkrétní varianta vybrána.

[NOTE]
====
Důvodem pro takto stanovené varianty je snaha zajistit v maximální možné míře dosažení účelu zkoušky (tzn. ověření, že student rozumí problematice reverzního inženýrství a například si nenechal domácí úlohy a semestrální práce vypracovat někým jiným) při dodržení rovných podmínek pro všechny (maximální omezení případných pokusů o podvádění), ale přitom co možná nejvíce eliminovat subjektivní vlivy a nemožnost dodatečného přezkoumání ústního zkoušení.
====

==== Varianta 1

Pokud *nebude* ke dni 4.1.2021 zakázáno (státem, ČVUT nebo FITem) konat prezenční akce v prostorách fakulty, parametry zkoušky se nemění.

==== Varianta 2

Pokud *bude* ke dni 4.1.2021 zakázáno (státem, ČVUT nebo FITem) konat prezenční akce v prostorách fakulty, parametry zkoušky se mění následujícím způsobem, a to bez výjimky pro všechny studenty, nezávisle na tom, zda budou nebo nebudou prezenční akce umožněny později v průběhu zkouškového období:

* Zkouška se bude konat online v prostředí MS Teams a bude ústní. Z technického vybavení je požadováno pouze natolik stabilní spojení, aby vydrželo po celou dobu zkoušky, a mikrofon.

* Zkouška potrvá 10 minut a bude na ní položena jedna otázka z probrané látky. Z důvodu minimalizace pokusů o podvody nebude prostor pro přípravu, student na položenou otázku okamžitě odpovídá.

* Zkouška nebude hodnocena body, ale binárně jako "úspěch" nebo "neúspěch". V případě neúspěchu bude student ohodnocen známkou F, jako kdyby v prezenční zkoušce získal 0 bodů. V případě úspěchu získá student za zkoušku tolik bodů, aby získal stejné procento z maximálního počtu, jako získal během semestru (jinými slovy, body ze semestru se vynásobí koeficientem 3/7 a matematicky zaokrouhlí na celé číslo).

==== Varianta 3

Pokud proběhne nejméně jeden zkouškový termín podle varianty 1 a následný vývoj epidemiologické situace vynutí přechod k variantě 2, budou mít studenti, kteří uspěli ve variantě 1, na výběr, jestli si přejí ponechat body získané ve variantě 1 a nebo jestli si nechají body ze zkoušky přepočítat, jako kdyby už od začátku zkouškového období probíhalo zkoušení podle varianty 2.

Opačný směr není možný, jakmile jednou vstoupíme do varianty 2, tato varianta zůstane v platnosti pro všechny další zkouškové termíny.

== Celkové hodnocení

Hodnocení se řídí aktuálním https://www.cvut.cz/vnitrni-predpisy[Studijním a zkušebním řádem ČVUT] ( https://www.cvut.cz/sites/default/files/content/74c76d2e-7f4d-4cb1-ac28-b0765c7f88f2/cs/20200624-studijni-a-zkusebni-rad-pro-studenty-cvut-v-praze-iii-uplne-zneni-ucinnost-od-11-3-2020_0.pdf[PDF] ).

[options="autowidth", cols=3*]
|====
<h| Známka
<h| Bodové +
rozmezí
<h| Slovní +
hodnocení

| A
| 90 a více
| výborně

| B
| 80 až 89.999
| velmi dobře

| C
| 70 až 79.999
| dobře

| D
| 60 až 69.999
| uspokojivě

| E
| 50 až 59.999
| dostatečně

| F
| méně než 50
| nedostatečně
|====
