
= NI-REV Reverzní inženýrství
:toc:
:imagesdir: ./media

* xref:en/index.adoc[English version]

== Aktuality

Sledujte prosím aktuální informace k výuce na stránce xref:current_info.adoc[Aktuality].

== Anotace

Studenti budou v rámci předmětu seznámeni se základy reverzního inženýrství počítačového softwaru. Dále studenti získají znalosti o tom, jakým způsobem probíhá spouštění a inicializace programu, co se odehrává před a po volání funkce main. Studenti také pochopí, jakým způsobem je organizován spustitelný soubor, jak se propojuje s Knihovnami třetích stran. Další část předmětu bude věnována reverznímu inženýrství aplikací napsaných v C++. Studenti se také seznámí s principy disassemblerů a obfuskačními metodami. Dále se předmět bude věnovat nástrojům pro ladění (debuggerům): jak ladící nástroje pracují, jak probíhá ladění a také se seznámí s metodami, které mohou být použity k detekci ladících nástrojů. Jedna z přednášek pohovoří o aktuální scéně počítačového škodlivého kódu. Důraz předmětu je kladen na cvičení, na kterých budou studenti řešit prakticky orientované úlohy z reálného světa.

== Učitelé

*Josef Kokeš*

* E-mail: mailto:josef.kokes@fit.cvut.cz[josef.kokes@fit.cvut.cz]
* Kancelář: TH:A-1137
* Konzultace: Podle potřeby, dohoda na termínu e-mailem nebo osobně na přednášce/cvičení.

== Hodnocení

* xref:evaluation.adoc[Podmínky absolvování předmětu]
* Průběžný stav bodů je uveden na webu https://grades.fit.cvut.cz[FIT klasifikace]. Ve vašem vlastním zájmu si kontrolujte hodnoty, které jsou tam uvedeny, a v případě zjištěných rozdílů mě kontaktujte, abych je opravil z "master" seznamu. Body na Klasifikaci jsou pouze orientační!

=== Termíny odevzdání úloh

[options="autowidth", cols=6*]
|====
<h| Úloha
<h| Body
<h| Zadáno
<h| Deadline +
Par.101
<h| Deadline +
Par.102
<h| Deadline +
Par.103

| xref:homeworks/email.adoc[E-mail]
| 5
| 3. týden
| 4.11. 17:45
| 5.11. 17:45
| 5.11. 19:30

| xref:homeworks/iat.adoc[IAT]
| 10
| 4. týden
| 18.11. 17:45
| 19.11. 17:45
| 19.11. 19:30

| xref:homeworks/snake.adoc[Had]
| 10
| 5. týden
| 9.12. 17:45
| 10.12. 17:45
| 10.12. 19:30

| xref:projects/crackme.adoc[Crackme]
| 25+
| 3. týden
| 13.2. 8:00
| 13.2. 8:00
| 13.2. 8:00

| xref:projects/keygen.adoc[Keygen]
| 20
| 1. týden
| 13.2. 8:00
| 13.2. 8:00
| 13.2. 8:00

| xref:labs/lab13.adoc[Bonus]
| 3
| 13. týden
| 13.2. 8:00
| 13.2. 8:00
| 13.2. 8:00
|====

== Změny v programu

Aktuálně žádné.

////
* *6. cvičení* (xref:labs/lab06.adoc[přednáška Martina Jirkala o malware]) se odsouvá na neurčito. Předpoklad je, že přednášky externích hostů budou provedeny na konci výukové části semestru nebo ve zkouškovém období (to pak ovšem ryze dobrovolně), pokud to bude možné.
* *7. cvičení* (xref:labs/lab07.adoc[konzultace + 64bitový kód]) se přesouvá do 6. týdne (29.10.).
* *8. cvičení* (xref:labs/lab08.adoc[jednoduché obfuskace]) se přesouvá do 7. týdne (5.11.).
* *9. cvičení* (xref:labs/lab09.adoc[složitější obfuskace]) se přesouvá do 8. týdne (12.11.).
* 19.11. výuka reverzního inženýrství odpadá, protože dle harmonogramu bude pondělí (náhrada za děkanský den 16.11.). *Pátá a šestá přednáška* se tak o dva týdny odsouvají (na 3.12. a 17.12.).
* 26.11. se bude konat *desáté cvičení* (unpacking).
* 3.12. budou dvě přednášky -- v regulérním čase od 12:45 *dokončení čtvrté přednášky* (obfuskace) a *pátá přednáška* (identifikování kompilátoru a knihoven), v čase prvního cvičení od 14:30 bude *šestá přednáška* (debugging a antidebugging). Cvičení od 16:15 a od 18:00 budou věnována konzultacím, pokud o ně bude zájem.
* 10.12. se bude konat *jedenácté cvičení* (antidebugging).
* 17.12. bude *externí přednáška Martina Jirkala* na téma malware a *třinácté cvičení* (injekce kódu).
* Pokud to bude jenom trochu možné, pokusím se o zkouškovém období uspořádat přednášku Jana Rubína na téma analýzy malware. Je to ale podmíněno možností ji uspořádat ve fyzické podobě, což je stále krajně nejisté -- zkoušky pravděpodobně bude možné fyzicky konat, protože je možné výrazně omezit počet lidí v místnosti, ale fyzická přednáška pro 40+ lidí se jeví jako velmi problematická.

* *7.-8.11.2019 (7. týden)*:
** Místo přednášky na *disassembling a obfuskace* bude mít Ing. Martin Jirkal z firmy ESET přednášku o *malware* (dle programu přednáška 7).
** Na cvičení bude místo přednášky na *malware* cvičení na *konzultace a 64bitový kód* (dle programu cvičení 7).
* *14.-15.11.2019 (8. týden)*:
** Na cvičení bude místo cvičení na *konzultace a 64bitový kód* přednáška na *disassembling a obfuskace* (dle programu přednáška 4).
* *12.-13.12.2019 (12. týden)*:
** Ing. Martin Jirkal povede cvičení na téma *analýza kódů v dotnetu*.
* *19.12.2019 (13. týden)*:
** Přednášku na téma *analýza malware* povede Ing. Jan Rubín z firmy Avast.
** link:{imagesdir}/lectures/rev08en.pdf[Přednáška].
** link:{imagesdir}/itsaunixsystem.zip[Crackme na vyzkoušení].
////

== Download

Offline verzi materiálů si můžete stáhnout zde: https://kib-files.fit.cvut.cz/mi-rev/offline.zip[Download]

Nástroje používané na cvičeních si můžete stáhnout zde: https://kib-files.fit.cvut.cz/mi-rev/nastroje/[Download]

Runtime knihovny pro různé verze Visual Studia si můžete stáhnout zde: https://kib-files.fit.cvut.cz/mi-rev/vcredist/[Download]

//Úvodní přednášky a cvičení z BI-BEK, kde si vysvětlujeme základy assembleru, naleznete zde: https://kib-files.fit.cvut.cz/bi-bek/BIK01-prednasky_1_2_cviceni_1_2.mp4[Download]
