
= NI-REV Reverzní inženýrství
:toc:
:imagesdir: ./media

* xref:en/index.adoc[English version]

== Anotace

Studenti budou v rámci předmětu seznámeni se základy reverzního inženýrství počítačového softwaru. Dále studenti získají znalosti o tom, jakým způsobem probíhá spouštění a inicializace programu, co se odehrává před a po volání funkce main. Studenti také pochopí, jakým způsobem je organizován spustitelný soubor, jak se propojuje s Knihovnami třetích stran. Další část předmětu bude věnována reverznímu inženýrství aplikací napsaných v C++. Studenti se také seznámi s principy disassemblerů a obfuskačními metodami. Dále se předmět bude věnovat nástrojům pro ladění (debuggerům): jak ladící nástroje pracují, jak probíhá ladění a také se seznámí s metodami, které mohou být použity k detekci ladících nástrojů. Jedna z přednášek pohovoří o aktuální scéně počítačového škodlivého kódu. Důraz předmětu je kladen na cvičení, na kterých budou studenti řešit prakticky orientované úlohy z reálného světa.

== Učitelé

*Josef Kokeš*

* E-mail: mailto:josef.kokes@fit.cvut.cz[josef.kokes@fit.cvut.cz]
* Kancelář: TH:A-1137
* Konzultace: Podle potřeby, dohoda na termínu e-mailem nebo osobně na přednášce/cvičení.

== Hodnocení

* xref:hodnoceni.adoc[Podmínky absolvování předmětu]
* Průběžný stav bodů je uveden na webu https://grades.fit.cvut.cz[FIT klasifikace]. Ve vašem vlastním zájmu si kontrolujte hodnoty, které jsou tam uvedeny, a v případě zjištěných rozdílů mě kontaktujte, abych je opravil z "master" seznamu. Body na Klasifikaci jsou pouze orientační!

=== Termíny odevzdání úloh

[options="autowidth", cols=6*]
|====
<h| Úloha
<h| Body
<h| Zadáno
<h| Deadline +
Par.101
<h| Deadline +
Par.102
<h| Deadline +
Par.103

| xref:labs/lab03.adoc[E-mail]
| 5
| 3. týden
| TBA
| TBA
| TBA

| xref:labs/lab04.adoc[IAT]
| 5
| 4. týden
| TBA
| TBA
| TBA

| xref:labs/lab05.adoc[Had]
| 5
| 5. týden
| TBA
| TBA
| TBA

| xref:projects/crackme.adoc[Crackme]
| 35+
| 3. týden
| 14.2. 8:00
| 14.2. 8:00
| 14.2. 8:00

| xref:projects/keygen.adoc[Keygen]
| 20
| 1. týden
| 14.2. 8:00
| 14.2. 8:00
| 14.2. 8:00

| xref:labs/lab13.adoc[Bonus]
| 3
| 4. týden
| 14.2. 8:00
| 14.2. 8:00
| 14.2. 8:00
|====

== Změny v programu

////
* *7.-8.11.2019 (7. týden)*:
** Místo přednášky na *disassembling a obfuskace* bude mít Ing. Martin Jirkal z firmy ESET přednášku o *malware* (dle programu přednáška 7).
** Na cvičení bude místo přednášky na *malware* cvičení na *konzultace a 64bitový kód* (dle programu cvičení 7).
* *14.-15.11.2019 (8. týden)*:
** Na cvičení bude místo cvičení na *konzultace a 64bitový kód* přednáška na *disassembling a obfuskace* (dle programu přednáška 4).
* *12.-13.12.2019 (12. týden)*:
** Ing. Martin Jirkal povede cvičení na téma *analýza kódů v dotnetu*.
* *19.12.2019 (13. týden)*:
** Přednášku na téma *analýza malware* povede Ing. Jan Rubín z firmy Avast.
** link:{imagesdir}/lectures/rev08en.pdf[Přednáška].
** link:{imagesdir}/itsaunixsystem.zip[Crackme na vyzkoušení].
////

== Download

Offline verzi materiálů si můžete stáhnout zde: https://kib-files.fit.cvut.cz/mi-rev/offline.zip[Download]

Nástroje používané na cvičeních si můžete stáhnout zde: https://kib-files.fit.cvut.cz/mi-rev/nastroje/[Download]

Runtime knihovny pro různé verze Visual Studia si můžete stáhnout zde: https://kib-files.fit.cvut.cz/mi-rev/vcredist/[Download]

Úvodní přednášky a cvičení z BI-BEK, kde si vysvětlujeme základy assembleru, naleznete zde: https://kib-files.fit.cvut.cz/bi-bek/BIK01-prednasky_1_2_cviceni_1_2.mp4[Download]
