
= 1. E-mail
:imagesdir: ../media/labs/03
:toc:

* Počet bodů: *5*
* Termín odevzdání:
** *03.11. 19:30* (paralelka 101)
** *04.11. 17:45* (paralelka 102)
** *04.11. 19:30* (paralelka 103)

Cílem úlohy je provést zpětnou analýzu souboru link:{imagesdir}/du1.zip[du1.zip] a přimět ho odeslat slušný e-mail cvičícímu. Program přijímá jako vstup konfigurační soubor, ten přiložený má ovšem nesprávnou strukturu i obsah. Analýzou programu zjistíte, jak má struktura souboru vypadat. Upravte konfigurační soubor tak, aby ho program interpretovat správně a aby cvičícímu poslal *slušný* e-mail. Při špatném formátu souboru může být odeslán neslušný e-mail, který není považován za správnou odpověď ;-).

Až se vám podaří odeslat požadovaný e-mail, pošlete cvičícímu na školní adresu použitý konfigurační soubor (zabalený v ZIPu, aby určitě nedošlo k nepozorovanému pozměnění jeho struktury během přenosu mailem) spolu se stručným popisem vašeho postupu. Jen samotné odeslání slušného e-mailu není hodnoceno jako splnění úlohy.

[IMPORTANT]
====
Samotný program `CrackMe01.exe` neměňte.
====

[NOTE]
====
Samotné odeslání e-mailu se ve skutečnosti nepodaří, protože knihovna `MailLibrary.dll` používá starší verzi protokolu TLS, která už není mailovým serverem akceptována. To nemusíte řešit -- jakmile se program jen na základě konfiguračního souboru dostane k použití funkce `MailSend`, je váš úkol splněn.
====
