
= 2. Import Address Table
:imagesdir: ../media/labs/04
:toc:

* Počet bodů: *10*
* Termín odevzdání:
** *27.11. 16:00* (paralelka 101)
** *27.11. 19:30* (paralelka 102)
** *28.11. 19:30* (paralelka 103)

Váš program, zkompilovaný pomocí MS Visual Studio, typicky používá externí runtime ve formě knihovny `MSVCRT12.DLL` (verze ve jménu se může lišit podle verze kompilátoru, tento název platí pro Visual Studio 2013). Tato knihovna obsahuje funkce `malloc`, `calloc`, `realloc` a `free`. Napište program, který bude obsahovat funkce:

* `MallocDebug_Init`
* `MallocDebug_Done`
* `MallocDebug_malloc`
* `MallocDebug_calloc`
* `MallocDebug_realloc`
* `MallocDebug_free`

Funkce `MallocDebug_Init` najde v IAT pozici funkcí `malloc`, `calloc`, `realloc` a `free` a změní jejich adresu na adresy funkcí `MallocDebug_malloc`, `MallocDebug_calloc`, `MallocDebug_realloc` a `MallocDebug_free` (tzv. substituční funkce).

Substituční funkce napište tak, aby si uložily záznam (stačí statické globální pole -- neřešíme konkurenční přístup více vláken ani podporu neomezeného množství alokací, stačí nám pevně dané maximum) o tom, že se alokovala paměť, a o její velikosti. Uvolňující substituční funkce budou tento záznam opět rušit (a stěžovat si, pokud by měly zrušit neznámou nebo uz dříve zrušenou alokaci). Substituční funkce samozřejmě také zavolají původní funkci, kterou substituují; pozor, v tomto volání nemůžete použít Cčkovou funkci `malloc` -- využijte ukazatele uložené v rámci `MallocDebug_Init`. Získáme tak schopnost logování paměťových alokačních/dealokačních operací.

Funkce `MallocDebug_Done` vrátí IAT do původního stavu a vypíše případné zbytky tabulky, které budou považovány za memory leaky :). Nezapomeňte vhodně otestovat, že vrácené údaje odpovídají skutečnosti (např. vytvořením úmyslného leaku).

== Řešení běžných problémů

[IMPORTANT]
====
Pokud vámi zkompilovaný program nepoužívá externí runtime knihovnu ale knihovnu staticky zakompilovanou přímo do spustitelného souboru, nebude úloha řešitelná. Můžete ale použít parametr `/MD`, kterým přimějete kompilátor k použití sdílené knihovny. Ověřte si v CFF Exploreru, že váš program importuje paměťové funkce!
====

[TIP]
====
*Zápis do IAT*

IAT je obvykle chráněna proti zápisu. Aby do ní bylo možné zapisovat, je nutné nejprve použít např. funkci link:https://msdn.microsoft.com/en-us/library/windows/desktop/aa366898(v=vs.85).aspx[VirtualProtect] a daný paměťový segment odemknout pro zápis.

[source,cpp]
----
BOOL WINAPI VirtualProtect (
  (LPVOID) lpAddress,   // adresa bloku, jehož stav ochrany chceme měnit
  (size_t) dwSize,      // velikost bloku
  PAGE_READWRITE,       // příznaky ochrany bloku
  (PDWORD)&dwOldProtect // stará hodnota příznaků
);
----
====

[TIP]
====
link:https://courses.fit.cvut.cz/BI-BEK/media/lectures/bek02cz.pdf[Druhá přednáška] a link:https://courses.fit.cvut.cz/BI-BEK/labs/lab02.html[druhé cvičení] z BI-BEK vám může pomoci, pokud se ztratíte v kompilaci a linkování.
====

== Typické chyby

[IMPORTANT]
====
Hlavním výstupem programu je výpis případů, kdy aplikace pracuje s pamětí špatně -- např. alokovala nějaký paměťový blok a už ho nikdy neuvolnila. Naproti tomu nepotřebujeme výpis jednotlivých prováděných operací (není chybou ho mít, ale sám o sobě není dostačujícím řešením úlohy).
====

[NOTE]
====
Při zpracování importního adresáře nemusíte řešit jiný obsah importního thunku než odkaz na `IMAGE_IMPORT_BY_NAME`, ale jinak musíte zpracovat libovolný, i poškozený, importní adresář. Upozornit, že adresář je vadný, a ukončit program je legitimní, spadnout na neplatný přístup do paměti tam, kde jste to mohli zpracováním dle specifikace ošetřit, nikoliv.
====

[NOTE]
====
Je naprosto přípustné, aby program importoval stejnou knihovnu -- a klidně i stejnou funkci z ní -- několikrát. Vaše řešení by s tím mělo počítat.
====

[IMPORTANT]
====
Cílem této úlohy *není*, abyste si napsali vlastní paměťový manager. Naopak by to bylo na škodu -- simulujeme případ, že chceme monitorovat chování programu ve specifické situaci, je tedy krajně nežádoucí do toho chování vnášet vlastní změny. Vaše implementace by měla zaznamenat údaje, které budete potřebovat, a potom (nebo před tím) zavolat originální verze paměťových funkcí.
====

[NOTE]
====
Vaše implementace by měla odpovídat specifikaci zaměňovaných funkcí. Nastudujte si dokumentaci a ujistěte se, že vaše řešení bude fungovat pro všechny možné mezní stavy, do kterých se paměťové funkce mohou dostat! Velmi častá chyba i u jinak perfektních řešení je, že student nedokázal pokrýt všechna použití paměťových funkcí -- zejména `realloc` má velmi široké možnosti využití!
====

[NOTE]
====
Počítejte s možností, že funkce `MallocDebug_Init` a `MallocDebug_Done` mohou být volány opakovaně a v libovolném pořadí.
====

[NOTE]
====
Pozor na kód, který naleznete online. Za prvé, pokud použijete cizí kód, měli byste ho správně citovat. Za druhé, cílem úlohy je, naučit se něco o chování importní tabulky; pokud použijete cizí kód, tak vám to v dosažení tohoto cíle nepomůže. Za třetí, cizí kód mnohdy sice funguje, ale nefunguje zcela správně. Pokud ho budete chtít použít, budu od vás chtít opravit chyby, které obsahuje, a to bude pravděpodobně obtížnější, než když si napíšete svůj vlastní kód od nuly.
====
