====== 1. Seznámení s nástrojem OllyDbg ======

Předmětem tohoto cvičení je seznámení se s ladícím nástrojem OllyDbg.

===== Zadání 1. zápočtové úlohy =====

  * Počet bodů: **5**
  * Termín odevzdání:
    * **31.10.2017, 16:00** (paralelka 101)
    * **31.10.2017, 19:30** (paralelka 102)

Cílem úlohy je provést zpětnou analýzu souboru {{:labs:01:crackme01-v3.zip|crackme01-v3.zip}} a přimět ho odeslat e-mail cvičícímu. Program přijímá jako vstup konfigurační soubor, ten přiložený má ovšem nesprávnou strukturu. Analýzou programu zjistíte, jak má struktura souboru vypadat, a upravte konfigurační soubor tak, aby ho program interpretovat správně a aby cvičícímu poslal **slušný** e-mail. Při špatném formátu souboru může být odeslán neslušný e-mail, který není považován za správnou odpověď ;-). Po správné interpretaci bude programem odeslán cvičícímu e-mail se slušným textem.

Až se vám podaří odeslat požadovaný e-mail, pošlete cvičícímu na školní adresu použitý konfigurační soubor (zabalený v ZIPu, aby určitě nedošlo k nepozorovanému pozměnění jeho struktury během přenosu mailem) spolu se stručným popisem vašeho postupu. Na základě těchto informací a případného zodpovězení doplňujících otázek vám budou připsány body za tuto úlohu.

<note important>Samotný program ''CrackMe01.exe'' neměňte.</note>

