
= 9. Analysis of an advanced obfuscation
:imagesdir: ../../media/labs/09
:toc:

== Materials

=== Collaborative websites cataloguing tools and scripts applicable to reverse analysis

* https://tuts4you.com/[www.tuts4you.com]
* http://www.woodmann.com/collaborative/tools/index.php/Category:RCE_Tools[www.woodmann.com]

=== An anti-debugging reference

* link:{imagesdir}/the_ultimate_anti-debugging_reference.pdf[The Ultimate Anti-debugging reference]

== Task 1

Analyze the attached application. Describe the obfuscation techniques used and modify the IDA Pro database to make the code human-readable. You can check the source code of the original (unobfuscated) application, but it's recommended you only use it to verify your findings; you should be able to analyze the application even without the source code.

* link:{imagesdir}/cv09a.zip[Download]

== Task 2

Open the attached application in a debugger and try to reach the end -- meaning the end after all the obfuscations, not the first `exit` you encounter :-). You may also analyze the application in IDA Pro and document all obfuscations -- that may be preferable as you won't need to search for a particular version of Windows XP or Vista.

* link:{imagesdir}/cv09b.zip[Download -- Win XP]
* link:{imagesdir}/cv09b.vista.zip[Download -- Win Vista]

== Tips for using IDA Free

If you use IDA Free for this, remember that you can use the `c` key to make a portion of data code, the `d` key to make a portion of code data, or the `u` key to undefine currently selected code or data. The `u` key is useful when you mess something up. Note that these keys work also with blocks.

You can perform changes to the program directly inside IDA Free. The patch menu is hidden by default in version 5.0. It is possible to show it but you'll need to change the configuration file located in `C:\Program Files (x86)\IDA Free\cfg\idagui.cfg`. Open the file as the Administrator and change the `ENABLE_PATCH_SUBMENU=NO` line into `ENABLE_PATCH_SUBMENU=YES`. Save and (re)launch IDA Free. Then you will find the Patch submenu in the Edit menu.
