
= 6. Consultations, 64bit code
:imagesdir: ../../media/labs/06
:toc:

* link:https://kib-files.fit.cvut.cz/mi-rev/recordings/2021/en/tutorial_07.mp4[Recorded tutorial]

This tutorial is primarily dedicated to consultations of your homeworks or other reverse-engineering related topics.

In the remaining time, we will study the differences between a 32bit and a 64bit code. We will use a simple 64bit application link:{imagesdir}/cv06.zip[cv06.zip].

. Open the application in a debugger.
. At the beginning of the application we can see a call to a function at offset `2268`. Try to understand what the function does. Then do the same thing in IDA Pro and compare the advantages and disadvantages of both approaches.
* Explain the meaning of the first instruction.
* Draw the stack frame, identify the variables and their use.
* What is the meaning of constant `2B992DDFA232h`?
* If we didn't call this function at all (e.g. if we replaced the `CALL` at the entry point with a sequence of `NOP` instructions), what would happen? Would the application still work? Or what would change in its behavior?
. Locate the `main` function.
* Notice that our `main` function does not use the `RBP` register at all. How is that possible?
* Why are arguments saved on the stack at the very beginning of the function?
* Identify the function's prologue. The remainder of the first basic block represents the beginning of the function's body. Explain the meaning of its instructions and propose how they would change if we were studying a 32bit program instead. Using a debugger, try to find out which instruction is responsible for clearing the top 32 bits of the `RAX` register.
* Identify the function's epilogue. Show how its instructions rlate to the instructions of the prologue.
* Try to estimate the meaning of the functions called from `main`. You don't need to study the functions themselves, in most cases you will find your information simply by looking at the function's arguments or observing the program's behavior at runtime.
. Locate some Windows API calls. From the lecture we know that Windows API is usually called with the `__stdcall` convention. Compare the calls to API functions with the calls to native C functions in our program. How do you explain your observations?
