
= 9. Analysis of an advanced obfuscation
:imagesdir: ../../media/labs/09
:toc:

* link:https://kib-files.fit.cvut.cz/mi-rev/MIE-tutorial_9.mp4[Recording of the tutorial]

== Materials

=== Collaborative websites cataloguing tools and scripts applicable to reverse analysis

* https://tuts4you.com/[www.tuts4you.com]
* http://www.woodmann.com/collaborative/tools/index.php/Category:RCE_Tools[www.woodmann.com]

=== An anti-debugging reference

* link:{imagesdir}/the_ultimate_anti-debugging_reference.pdf[The Ultimate Anti-debugging reference]

== Task 1

Analyze the attached application. Describe the obfuscation techniques used and modify the IDA Pro database to make the code human-readable. You can check the source code of the original (unobfuscated) application, but it's recommended you only use it to verify your findings; you should be able to analyze the application even without the source code.

* link:{imagesdir}/cv09a.zip[Download]

== Task 2

Perform a static analysis of the attached application in IDA Pro. Describe the obfuscation techniques you encounter and modify the IDA database to make the code human-readable. We will make use of this readable code in two weeks because it will reveal the hidden antidebugging techniques. We will then be able to determine conditions required to make the application run in its entirety. (We may not be able to actually run the application because parts of it are heavily system-dependent.)

* link:{imagesdir}/cv09b.zip[Download -- Win XP]
* link:{imagesdir}/cv09b.vista.zip[Download -- Win Vista]

== Tips for using IDA Free

=== Useful keyboard shortcuts

When removing obfuscations, you may find the following keyboard shortcuts useful:

* kbd:[D] -- makes IDA interpret the selected line or block as data rather than code.
* kbd:[C] -- makes IDA interpret the selected line or block as code rather than data.
* kbd:[U] -- makes IDA forget what you said before and treat the selected line or block as it would without your interventions.
* kbd:[P] -- tells IDA that the block should be considered a separate procedure.
** This is very useful in case of obfuscated function -- then IDA usually only recognizes a part of the function, up until the first obfuscation. After you've removed the obfuscation (e.g. by converting it to data or patching it out) you can ask IDA to regenerate the function.
** Sometimes kbd:[P] alone won't be sufficient. In that case undefine (kbd:[U]) the function's first label (i.e. its name) and then use kbd:[P] on this label.

[IMPORTANT]
====
Until version 7.3 IDA had no support for undo. By using the keys above (and many others) you can seriously damage your work. Save often, preferably to different files, so that you have something to return to!
====

=== Changing the executable in IDA

You can perform changes to the program directly inside IDA Free. The patch menu is hidden by default in version 5.0. It is possible to show it but you'll need to change the configuration file located in `C:\Program Files (x86)\IDA Free\cfg\idagui.cfg`. Open the file as the Administrator and change the `ENABLE_PATCH_SUBMENU=NO` line into `ENABLE_PATCH_SUBMENU=YES`. Save and (re)launch IDA Free. Then you will find the Patch submenu in the Edit menu.
