
= 1. E-mail
:imagesdir: ../../media/labs/03
:toc:

* Points: *5*
* Deadline: *November 4, 16:00*

The goal of this homework is to reverse engineer file link:{imagesdir}/du1.zip[du1.zip] and convince it to send an e-mail to the teacher. The program uses a configuration file, but the provided one is incorrect. By the time you finish analyzing the application, you will learn the correct structure and content of the configuration. Then create a file that will cause sending of a *polite* e-mail. If you make an error, an impolite e-mail might get sent -- but that is not considered a correct solution ;-).

After you've managed to send the correct e-mail, send the teacher your config file (packed into ZIP, so that any modification by e-mail servers or clients can be detected) along with a brief description of your work (how you got this file). The polite e-mail itself is not a solution of the homework, it's just a notification for you that you got it right.

[IMPORTANT]
====
Do not modify the `CrackMe01.exe` application.
====

[NOTE]
====
The sending of the e-mail will actually fail, because the `MailLibrary.dll` library uses an older version of the TLS protocol which is no longer accepted by the mail server. You don't need to worry about that -- if the program can reach the `MailSend` function just based on the instructions in the configuration file, your job is done.
====
