= 8. Analýza programu s jednoduchou obfuskací 
:imagesdir: ../../media/labs/08


Předmětem cvičení je analýza programů s jednoduchou obfuskací.

Programy, se kterými budeme pracovat, jsou dostupné zde: link:{imagesdir}/cv5.zip[cv5.zip]. Pro jejich spuštění budete potřebovat 32bitovou verzi https://www.microsoft.com/en-us/download/details.aspx?id=5555[Visual Studio 2010 Runtime].

Vaším úkolem je najít pro každý z programů vstup, který bude neupraveným programem přijat. Může se stát, že budete potřebovat v zájmu usnadnění analýzy některá místa programů dočasně upravit – to je přípustné, ale pouze za předpokladu, že vámi nalezené řešení bude následně fungovat i v neupravených programech. Lze se však obejít i bez úprav: použitou ochranu proti reverzování lze snadno obejít i bez úprav programu, navíc algoritmy jsou natolik jednoduché, že je lze snadno pochopit i pomocí statické analýzy.


== Tipy pro použití programu IDA


Klávesou `c` můžete říci analýzátoru, aby se k dané oblasti dat choval jako ke kódu. Naopak klávesou `d` můžete z kódu udělat data. Klávesou `u` můžete zrušit přiřazení kód/data a vrátit implicitní chování – to se hodí zejména v případě, kdy něco v programu rozhodíte.

V programu IDA můžete přímo měnit analyzovaný program nástroji v menu Patch. Toto menu je ve Free verzi standardně skryté, ale můžete ho zobrazit, pokud změníte konfigurační soubor `C:\Program Files (x86)\IDA Free\cfg\idagui.cfg`: otevřete soubor v editoru jako Administrátor a změňte řádek `ENABLE_PATCH_SUBMENU=NO` na `ENABLE_PATCH_SUBMENU=YES`. Po restartu IDA Free naleznete nové submenu Patch v menu Edit.
