
= 9. Analýza programu se složitější obfuskací
:imagesdir: ../media/labs/09
:toc:

== Materiály

=== Kolaborativní weby sdružující nástroje a skripty na reverzování chráněných souborů

* https://tuts4you.com/[www.tuts4you.com]
* http://www.woodmann.com/collaborative/tools/index.php/Category:RCE_Tools[www.woodmann.com]

=== Dokument popisující různé anti-debug techniky

* link:{imagesdir}/the_ultimate_anti-debugging_reference.pdf[The Ultimate Anti-debugging reference]

== Úkol 1

Zanalyzujte přiložený program, popište různé použité obfuskace a upravte databázi programu IDA Pro tak, aby byla čitelná člověkem. K dispozici máte i původní zdrojový kód (bez použitých obfuskací), který můžete použít pro kontrolu dosažených výsledků. Doporučuji však aplikaci napřed prozkoumat bez této pomůcky.

* link:{imagesdir}/cv09a.zip[Download]

== Úkol 2

Proveďte statickou analýzu programu v IDA Pro. Popište použité obfuskace a upravte databázi IDY tak, aby byl kód čitelný člověkem. V této podobě využijeme databázi za dva týdny, kdy nám čitelný kód umožní rozpoznat použité antidebugovací techniky a stanovit podmínky, za kterých program proběhne až na konec. (Skutečné spuštění programu patrně nedokážeme dokončit, protože je v některých částech silně systémově závislý.)

* link:{imagesdir}/cv09b.zip[Download -- Win XP]
* link:{imagesdir}/cv09b.vista.zip[Download -- Win Vista]

== Tipy pro použití programu IDA

=== Užitečné klávesové zkratky

Při odstraňování obfuskací se vám mohou hodit následující klávesové zkratky pro program IDA.

* kbd:[D] -- způsobí, že bude IDA vybraný řádek nebo blok považovat za data a ne za kód.
* kbd:[C] -- způsobí, že bude IDA vybraný řádek nebo blok považovat za kód a ne za data.
* kbd:[U] -- způsobí, že IDA zapomene dosavadní definice řádku/bloku a vrátí se k implicitnímu chování.
* kbd:[P] -- informuje IDU, že má daný blok chápat jako samostatnou proceduru.
** Toto se velmi hodí v případě, že máme obfuskovanou funkci, ze které IDA rozpozná jenom část až do první obfuskace. Po odstranění obfuskace (např. převodem na data nebo patchováním) můžeme nechat funkci vygenerovat znovu.
** Pokud samotné kbd:[P] nezabere, je vhodným postupem provést undefine (kbd:[U]) na prvním návěští procedury (tzn. na jejím jménu) a následně použít kbd:[P] znovu na toto návěští.

[IMPORTANT]
====
IDA až do verze 7.3 neobsahuje podporu pro vrácení posledního kroku (undo). Nevhodným použitím těchto kláves (a také řady dalších) si můžete celou dosavadní práci těžce nabořit. Ukládejte často, pokud možno do různě pojmenovaných souborů, ať se máte k čemu vrátit!
====

=== Změny programu přímo v IDA

V programu IDA můžete přímo měnit analyzovaný program nástroji v menu Patch. Pokud používáte verzi 5.0 Free, je toto menu standardně skryté, ale můžete ho zobrazit, pokud změníte konfigurační soubor `C:\Program Files (x86)\IDA Free\cfg\idagui.cfg`: otevřete soubor v editoru jako Administrátor a změňte řádek `ENABLE_PATCH_SUBMENU=NO` na `ENABLE_PATCH_SUBMENU=YES`. Po restartu IDA Free naleznete nové submenu Patch v menu Edit.
