
= 11. Anti-debugging
:imagesdir: ../media/labs/11
:toc:

Na tomto cvičení budeme analyzovat program odkazovaný níže. Tento program po svém spuštění uloží na disk obrázek `picture.jpg` a následně se ukončí.

Při analýze programu narazíme na to, že program obsahuje několik ochran proti debugování. Mimo jiné se jeho struktura mění za běhu, takže je nečitelný při statické analýze. Úkolem je zjistit, jak ochrany programu fungují, a následně program upravit tak, aby na disk uložil jiný obrázek z resource sekce programu. V první fázi to můžeme provést v debuggeru, cílové řešení by ale mělo zahrnovat takový zásah do programu, aby se alternativní obrázek ukládal vždy.

* link:{imagesdir}/cv11.zip[Download]

== Další anti-debuggingové techniky

Vraťte se k druhé úloze z xref:lab09.adoc[cvičení na pokročilé obfuskace]. Deobfuskujte jeho kód a identifikujte jednotlivé anti-debuggingové techniky, které používá.

== Zapnutí patch menu v IDA Free

V programu IDA můžete přímo měnit analyzovaný program nástroji v menu Patch. Pokud používáte verzi 5.0 Free, je toto menu standardně skryté, ale můžete ho zobrazit, pokud změníte konfigurační soubor `C:\Program Files (x86)\IDA Free\cfg\idagui.cfg`: otevřete soubor v editoru jako Administrátor a změňte řádek `ENABLE_PATCH_SUBMENU=NO` na `ENABLE_PATCH_SUBMENU=YES`. Po restartu IDA Free naleznete nové submenu Patch v menu Edit.
