
= 10. Rekonstrukce zabalených binárních souborů
:imagesdir: ../media/labs/10
:toc:

V tomto cvičení se seznámíme s metodami a nástroji, které dokáží vytvořit dump z paměti počítače a tento dump pak rekonstruovat tak, aby byl spustitelný (a analyzovatelný).

== Obecný postup pro manuální rozbalování souborů

Pozn.: Návod se může lišit dle použitého packeru, v extrémních případech může být silně nedostatečný! (Themida packer apod.)

. Spusťte zabalený soubor v debuggeru. Na rozdíl od původního nezabaleného souboru se nyní spouští rozbalovací rutina, na kterou ukazuje Entry Point (EP). Snažte se naleznout Original Entry Point (OEP) -- místo, kde by program prováděl svoji první instrukci, kdyby nebyl zabalený --, a na tomto místě zastavte debugger.
. Vytvořte dump procesu. Můžete manuálně zkopírováním z RAM, ale je lepší použít jeden z mnoha programů na internetu. Často se používá LordPE, můžete využít i některý z novějších nástrojů -- Scylla (je i součástí x64dbg), InjDmp, atd.
. Je možné, že data dumpnutého procesu nebudou pozičně sedět (na adrese `40162b` má být call, ale je tam něco jiného!). Důvodem je, že na sebe nesedí virtuální a fyzická adresa tak, jak mají. Buď můžete použít nástroj na rekonstrukci souboru (Scylla, PE tools, měl by to umět LordPE), nebo prostě změňte fyzickou adresu každé sekce tak, aby byla stejná jako virtuální adresa, a to samé udělejte s velikostmi sekcí. Tím zajistíte, že bude loader brát kód ze správné části vyrobeného fyzického souboru.
. Dump má nastavený špatný EP a nemá správně vytvořenou IAT. Na opravu obojího lze použít nástroje na rekonstrukci IAT. Často se používá ImpRec, my v hodině využijeme nástroj Scylla integrovaný do x64dbg. Nástroje obecně fungují tak, že na vstupu dostanou (nebo automaticky naleznou) IAT běžícího procesu a podle této funkční IAT pak vytvoří novou sekci Import Directory v dumpovaném souboru.

=== Několik osobních zkušeností od Martina Jirkala

* Některé dumpery vytvářejí dump, který není úplně vhodný na zpracování. Je to ojedinělé, ale stává se to. Pokud vše děláte správně a import reconstructor přesto nefunguje, často stačí změnit program na dump procesu z paměti.
* Velká část nástrojů nedokáže vytvořit dump z procesu, který je v SUSPENDED stavu. Například u druhé úlohy, kde máte rozbalit injektovaný kód, je LordPE na vytvoření dumpu z procesu nevhodný. Je ale dostatečný, chcete-li soubor získat ještě před injektáží z injektovacího procesu.
* Pokud vás zlobí ASLR, tak v hlavičce `IMAGE_OPTIONAL_HEADER` souboru změňte atribut `DllCharacteristics` tak, aby neobsahoval flag `IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE` (v některých nástrojích nazývaný též „DLL can move“).*

=== Návod pro x64dbg

* V menu x64dbg zvolte *Plugins -> Scylla*.
* Nastavte položku *OEP* na nalezenou adresu Original Entry Pointu.
* Tlačítkem *IAT AutoSearch* nalezněte odpovídající IAT. V případě neúspěchu můžete její virtuální adresu (VA) a délku (Size) nastavit ručně.
* Tlačítkem *Get Imports* načtěte importy odpovídající této IAT. Případné vadné záznamy můžete oeditovat nebo smazat.
* Tlačítkem *Dump* uložte proces z paměti na disk. V tuto chvíli ještě nejde o běžně spustitelný soubor!
* Tlačítkem *Fix Dump* tento nově vytvořený soubor opravíte do finálního stavu se zrekonstruovanými importy.

=== Návod pro OllyDbg + OllyDumpEx

Pro dump souboru použijeme debugger OllyDBG a skript OllyDumpEx.

* Pozor, některé verze Olly dokáží rozpoznat UPX a začinájí již na OEP. Soubor sice není rozbalený, ale disassembly tak vypadá.
* Použijte pro dump plugin/script OllyDumpEx.
* Máme vyzkoušeno, že Scylla Import Reconstructor funguje i na Windows 10.

== Úlohy k procvičení

Stáhněte si link:{imagesdir}/cv10.zip[cv10.zip].

=== CV11-packed.exe

Cílem této úlohy je seznámit se s nástroji a postupy pro rekonstrukci zabaleného souboru. Máme k dispozici program zabalený pomocí UPX, který chceme analyzovat. Pro to je nutné nejprve soubor rozbalit, protože jinak je viditelný pouze dekompresní kód, ale ne jádro aplikace. Vytvořte na disku nový soubor, který obsahuje pouze toto jádro bez dekompresního obalu.

[NOTE]
====
Nejjednodušší by samozřejmě bylo soubor rozbalit přímo pomocí UPX, které tuto funkcionalitu také obsahuje. Ne vždy ale máme tu možnost, proto v této úloze použijeme ruční postup. Pro zkrácení analýzy si můžete všimnout, že první instrukce dekompresní rutiny je `PUSHAD` pro uložení (většiny) registrů na zásobník; lze očekávat, že těsně před zavoláním OEP budou registry opět obnoveny pomocí `POPAD`; tento odhad pak můžete potvrdit prozkoumáním prvních funkcí v předpokládáném OEP (zda mají strukturu, jakou očekáváme od funkce `start`).
====

=== CV11-injector.exe

Chceme prozkoumat program, který používá speciální injektační techniku, tzv. hollowing, pro zamaskování své činnosti: Program načte to paměti zcela neškodnou a pokud možno nenápadnou aplikaci (např. svchost.exe nebo iexplore.exe), ale ještě před jejím spuštěním z ní zcela odstraní původní kód a načte do ní kód svůj. Poté aplikaci spustí. Uživatel pak vidí pouze data odpovídající původní aplikaci, ve skutečnosti se ale provádí kód malwaru.

Bližší informace o technice naleznete na stránce https://www.trustwave.com/Resources/SpiderLabs-Blog/Analyzing-Malware-Hollow-Processes/[Analyzing Malware Hollow Processes] (link:{imagesdir}/hollow.mht[lokální kopie]).

V naší úloze je program pro jednoduchost rozdělen na dvě části: `CV11-injector.exe` je nástroj, který provádí injektáž do jiného procesu. `data.bin` je kód, který bude injektovaný. Analýza tohoto kódu je pak ovšem triviální -- rovnou ho máme na disku, stačí ho načíst do debuggeru. Opět zde ale simulujeme případ, kdy takovýto luxus nemáme -- data se nachází zkomprimovaná a zašifrovaná někde uvnitř injektážní aplikace, která je napřed v paměti rozbalí a potom vloží do nového procesu. My je ovšem potřebujeme pro další analýzu dostat na disk ve spustitelné podobě.

Nejjednodušší je, nalézt v paměti kód programu a ten uložit jako jeden velký blok dat rovnou na disk. V naší aplikaci to je schůdná cesta, protože konec konců přesně tak ten blok v paměti vznikl -- že jsme ho ze spustitelného souboru jako celek načetli. Ne vždy je ale tato technika použitelná, můžeme proto použít alternativní řešení: Necháme injektovací program, aby si spustil proces oběti a nahradil jeho kód svým kódem. Těsně před spuštěním (např. pomocí API `ResumeThread`) se pak pokusíme provést dump nového procesu. Pokud se to nepodaří, což je velmi pravděpodobné (viz poznámka o SUSPENDED výše), můžeme nahradit první instrukci injektovaného programu instrukcí `INT3` (s kódem `0xCC`) a nechat proces spustit. Operační systém narazí na breakpoint a buď aplikaci ukončí, nebo -- pokud existuje debugger zaregistrovaný jako Just In Time debugger -- nabídne ladění. Máme tedy možnost ještě před vlastním spuštěním programu, *ale po provedení dynamického linkování*, spustit debugger a v něm proces dumpnout obvyklým způsobem. Samozřejmě je vhodné pak do výsledného souboru místo `INT3` zapsat původní instrukci.

[NOTE]
====
Ve Windows 10 došlo ke změně v chování just-in-time debuggeru. V dřívějších verzích při chybě programu vyskočilo okno s dotazem, co se má stát, a jednou z možností bylo právě debugování chybujícího procesu. Ve Windows 10 se aplikace rovnou ukončí. Způsob, jak vyvolat původní chování, neznám, ale můžete zapnout automatickou aktivaci just-in-time debuggeru tak, že v registru `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AeDebug` (resp. `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\AeDebug` pro 32bitové programy na 64bitových Windows) změníte hodnotu položky `Auto` z `0` na `1`.
====

== Vhodné nástroje

* http://woodmann.com/collaborative/tools/images/Bin_LordPE_2010-6-29_3.9_LordPE_1.41_Deluxe_b.zip[LordPE] -- oblíbený nástroj pro úpravu PE souborů a pro dump z paměti.
* https://tuts4you.com/download.php?view.3503[Scylla Imports Reconstructor] -- nástroj pro rekonstrukci IAT v binárním souboru.
* https://www.aldeid.com/wiki/PEiD[PEiD] -- nástroj pro detekci packerů.
* http://processhacker.sourceforge.net/[Process Hacker] -- alternativa pro Process Explorer.
* https://hooked-on-mnemonics.blogspot.com/p/injdmp.html[InjDmp] -- velmi pěkný nástroj na dumpování procesů.
* https://x64dbg.com[x64dbg] -- výborný debugger, včetně pluginu Scylla Imports Reconstruction.
