= 9. Analysis of an Obfuscated Binary II 
:imagesdir: ../../../media/en/labs/09


Collaborative websites cataloguing tools and scripts applicable to reverse analysis:

* https://tuts4you.com/[www.tuts4you.com]
* http://www.woodmann.com/collaborative/tools/index.php/Category:RCE_Tools[www.woodmann.com]

An anti-debugging reference:

* link:{imagesdir}/../../../labs/09/the-ultimate-anti-debugging-reference.pdf[The Ultimate Anti-Debugging Reference]


== Task 1


Analyze the attached application. Describe the obfuscation techniques used and modify the IDA Pro database for a human-readability. You can check the source code to the original (unobfuscated) application, but it's recommended you only use it to verify your findings; you should be able to analyze the application even without the source code.

* link:{imagesdir}/../../../labs/09/cv-7-crackme-1.zip[Crackme 7.1]


== Task 2


Open the attached application in a debugger and try to reach the end – meaning the end after all the obfuscation, not the first `exit` you encounter :-). You may also analyze the application in IDA Pro and document all obfuscations – that may be preferable as you won't need to search for a particular version of Windows XP or Vista.

* link:{imagesdir}/../../../labs/09/cv-7-crackme-2.zip[Crackme 7.2 for Windows XP]
* link:{imagesdir}/../../../labs/09/cv-7-crackme-2-vista.zip[Crackme 7.2 for Windows Vista]


== Tips for using IDA Free


If you use IDA Free for this, remember that you can use the `c` key to make a portion of data code, the `d` key to make a portion of code data, or the `u` key to undefine currently selected code or data. The `u` key is useful when you mess something up. Note that these keys work also with blocks.

You can perform changes to the program directly inside IDA Free. The patch menu is hidden by default. It is possible to show it but you'll need to change the configuration file located in `C:\Program Files (x86)\IDA Free\cfg\idagui.cfg`. Open the file as the Administrator and change the `ENABLE_PATCH_SUBMENU=NO` line into `ENABLE_PATCH_SUBMENU=YES`. Save and (re)launch IDA Free.
